### ISSUE TITLE
Can the user login using many extensions in same Time

### ISSUE THREAD

**Issue by mgw2007** [ringcentral/ringcentral-web-phone#100]
Hi
I have a case that the user can have many extensions in same time 
I found in your code  you can login by one extension or not
`login({
                username: login,
                extension: ext || null,
                password: password
            })`
Is there is away to login with many extensions 
I mean some thing like this
`login({
                username: login,
                extension: [ext1, ext2 , ext3],
                password: password
            })`
Is it possible 
If not possible what I can use to solve this issue , should I call login method for each extension ?

**Comment by LingForCC** [comment]
I am afraid that you can not do that. What is the use case? Could you elaborate a bit more?

**Comment by mgw2007** [comment]
my case the user have to answers all calls come to specific extensions 
and the user need to login on these extensions to receive calls

**Comment by LingForCC** [comment]
Do those extension belong to one account? One possible solution is to forward all those calls to one extension.

**Comment by mgw2007** [comment]
my case can be many accounts with many extension 
How can I manage forward calls to one  extension ? This can be managed by API or from the ringcentral.com portal ?

**Comment by LingForCC** [comment]
Yes. You can do that in service.ringcentral.com.

**Comment by mgw2007** [comment]
ok 
I will check it may be can solve my issue

**Comment by grokify** [comment]
I'm going to close this now since it has been idle for a while. Please feel free to post here if this issue comes up again.
