### ISSUE TITLE
Implement Methods for Monitor, Whisper, Barge 

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-web-phone#101]
Implement methods for monitor, whisper, barge and takeover.

The [README.md](https://github.com/ringcentral/ringcentral-web-phone#bargewhisper) indicates that barge and whisper can be done with the WebRTC webphone SDK by dialing `*83` and it would it be nice to have methods for each.

> **Barge/Whisper**
> Not yet implemented. Could be done by dialing *83. The account should be enabled for barge/whisper access through system admin.

Here is more information on these capabilities from [KB article 8086](https://success.ringcentral.com/articles/en_US/RC_Knowledge_Article/8086):

> Silent Monitoring:
> Dial *80 to monitor a call. When prompted, enter the extension you need to monitor and press pound. Call monitoring allows you to listen to all parties in an active call without transmitting any audio yourself.
> 
> Whisper/Coach:
> Dial *81 for call coaching. When prompted, enter the extension you wish to coach and press pound. Call coaching allows you to speak directly to the extension you are coaching while they are in a call, without transmitting audio to the other party.
> 
> Barge:
> Dial *82 for call barge. When prompted, enter the extension you wish to barge and press pound. Call barging allows you to join another extension's in-progress call and communicate with all parties as if you were added via intercom.
> 
> Takeover:
> Dial *83 for call takeover. When prompted, enter the extension you wish to takeover and press pound. Call takeover allows you to disconnect an extension while they are in a call and take their place as an active call party member.

A request for this has been made on the Dev Community:

* https://devcommunity.ringcentral.com/ringcentraldev/topics/monitor-calls

**Comment by tylerlong** [comment]
Added some comments to the readme file: https://github.com/ringcentral/ringcentral-web-phone?tab=readme-ov-file#monitorwhisperbargecoachtake-over

It is supported without problems.
