### ISSUE TITLE
How can I show the caller phone number?

### ISSUE THREAD

**Issue by mgw2007** [ringcentral/ringcentral-web-phone#102]
Hi
I found that I can use `session.request.from.displayName` && `session.request.from.uri.user` to show the caller information, but How can I show the caller phone number?

**Comment by vyshakhbabji** [comment]
We are already displaying the caller phone number . Please have a look at our demo app here: https://github.com/ringcentral/ringcentral-web-phone/blob/master/demo/index.js#L175

For further investigation send us an email at devsupport@ringcentral.com.
