### ISSUE TITLE
Set call unhold failed in case two calls in same line 

### ISSUE THREAD

**Issue by mgw2007** [ringcentral/ringcentral-web-phone#106]
DOMException: Failed to set local answer sdp: Failed to push down transport description: Offerer must use actpass value for setup attribute.

In case I connected using ext(X)
then received call from another ext(Y) and I accept the call
then another ext(Z) called me so before I receive the call I set ext(Y) hold
then I accept the call from ext(Y) and after I finished the call with ext(Y) I ended the call with ext(Y)
then I return to call from  ext(Z) to back the call and put it unhold
I received this error  :
**DOMException: Failed to set local answer sdp: Failed to push down transport description: Offerer must use actpass value for setup attribute.**

Any help

**Comment by vyshakhbabji** [comment]
I could not reproduce the issue. Please send the full session logs to devsupport@ringcentral.com. I will look into it .
