### ISSUE TITLE
Call Recording Issue

### ISSUE THREAD

**Issue by mgw2007** [ringcentral/ringcentral-web-phone#107]
Hi
The recording can work only if the call receiver accept the call 
If I start record before he accept the call I see this error {code: -4, description: "State is not accepted for processing"}
and if this error happened one time I can not start record even if the call receiver accept the call because I see this {code: -6, description: "The same operation in progress"}
![screenshot from 2017-01-21 11 26 45](https://cloud.githubusercontent.com/assets/949904/22173478/83b4f5d2-dfcd-11e6-8418-8be4233438b5.png)

**Comment by kirill-konshin** [comment]
Please use devsupport@ringcentral.com for API questions. We address only code issues of this repo here.
