### ISSUE TITLE
Warm Transfer

### ISSUE THREAD

**Issue by alexgritton** [ringcentral/ringcentral-web-phone#110]
I ran into an issue with the Warm Transfer in the blindTransfer function on this part:
`
                      timeout = setTimeout(function() {
                            reject(new Error('Timeout: no reply'));
                            session.removeListener('RC_SIP_NOTIFY', onNotify);
                        }, responseTimeout);
                        session.on('RC_SIP_NOTIFY', onNotify);`

The timeout was hit every time and the transfer wouldn't complete.

As a work around I've been using the transfer functionality built into sipjs.
Instead of calling `resolve(session.warmTransfer(newSession));` 
I call `session.unhold().then(function(){
      resolve(session.refer(newSession));
}`

I found that if I didn't unhold the session first then it would complete the transfer but the session would still be on hold.

I'm not sure why there is a custom blindTransfer function in ringcentral-web-phone.js, but the sipjs function refer works just fine for both blind and attended transfers.

**Comment by kirill-konshin** [comment]
Some time ago RC servers were unable to correctly parse the headers generated by `session.refer` so there was a custom function for that. I will verify the current behavior as well as your proposal and get back to you.

**Comment by vyshakhbabji** [comment]
Hi Alex ,

For further investigation,  we need SIP logs and also certian clarifications . Please reach me out at devsupport@ringcentral.com.

Vyshakh
