### ISSUE TITLE
Could not able to hear voice

### ISSUE THREAD

**Issue by srigottipati** [ringcentral/ringcentral-web-phone#112]
Hi,

I am making call with WebRTC and not able to hear any voice for both inbound/outbound calls.it was working fine and suddenly it stopped working.

Getting all notification including connected,ringing and not getting any error.

any idea?

thanks in advance for help.

Sri

**Comment by kirill-konshin** [comment]
Please use devsupport@ringcentral.com, attach all information that you have: account details, call information, browser info, logs. This issue tracker is for code-related stuff.
