### ISSUE TITLE
Couldn't login

### ISSUE THREAD

**Issue by KUMARESAN-MUPPIDATHI** [ringcentral/ringcentral-web-phone#115]
When i click on Login button in demo, im getting below error
{
  "error" : "unauthorized_client",
  "errors" : [ {
    "errorCode" : "OAU-251",
    "message" : "Unauthorized for this grant type"
  } ],
  "error_description" : "Unauthorized for this grant type"
}

Should i need to change any configuration in MyApp?
Any suggestions regarding this would be great.

Thanks in Advance.

**Comment by andola-dev** [comment]
I am also facing same issue. Please suggest

**Comment by vyshakhbabji** [comment]
You should use 3 legged auth flow for logging in. Please use Application Type as "Browser Based". We have included demo to support this. Closing the case.
