### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by andola-dev** [ringcentral/ringcentral-web-phone#116]
I am trying to use demo js scripts for RingCentral, followed all the steps including digital line setup with extension. 
Getting the following here,
**Error: Unauthorized for this grant type**

I even tried using ringcentral softphone for desktop, working fine with the same credentials. Please suggest.

**Comment by andola-dev** [comment]
{
  "error" : "unauthorized_client",
  "errors" : [ {
    "errorCode" : "OAU-251",
    "message" : "Unauthorized for this grant type"
  } ],
  "error_description" : "Unauthorized for this grant type"
}

**Comment by andola-dev** [comment]
I tried creating the application in ringcentral as  Server(no UI) and now seems this is working fine.

**Comment by vyshakhbabji** [comment]
You should use 3 legged auth flow for logging in. Please use Application Type as "Browser Based".  We have included demo to support this. Closing the case.
