### ISSUE TITLE
Is there a way to check error when registering?

### ISSUE THREAD

**Issue by LingForCC** [ringcentral/ringcentral-web-phone#124]
As RingCentral webRTC server supports 5 clients only, when the 6th client tries to register with server, server returns the 'Too Many Contacts' error. Is there a way to get this error outside? The reason we need this is that we would like to detect this error and show corresponding warning messages in our app.

**Comment by kirill-konshin** [comment]
What do you mean "get this error outside"? What is the current behavior?

**Comment by LingForCC** [comment]
As shown in the screenshot, the server returns 'Too Many Contacts' error when 6th client registers. But it seems that there isn't a way to get this error from webphone sdk.

![image](https://cloud.githubusercontent.com/assets/5373202/26040000/b5b861a6-3953-11e7-9269-c15d030fd389.png)

**Comment by kirill-konshin** [comment]
There has to be an event for that in SiP.JS, it's instance is available in WP SDK. Please perform initial investigation what functionality could be used and either make a PR or request a change.

**Comment by vyshakhbabji** [comment]
Please use below code to figure out the error causes:

```
session.on('failed', function (request) {
  var cause = request.cause; //sometimes this is request.reason_phrase
  if (cause === SIP.C.causes.XXXXXXX) {
         //code
  }
});
```

For registration failure , you can use this 

```
session.on('registrationFailed', function (response, cause) {
       //code
}) 
```

For more info please view sipJS API documentation : https://sipjs.com/api/0.7.0/
