### ISSUE TITLE
DOMException: The play() request was interrupted by a call to pause() - The whole app breaks after this(Can't make incoming/outgoing calls).

### ISSUE THREAD

**Issue by mangatinanda** [ringcentral/ringcentral-web-phone#129]
This happens sporadically but when it does, it breaks everything 😞 
`Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().` This shows up in the console. 

[This stackoverflow question](https://stackoverflow.com/questions/36803176/how-to-prevent-the-play-request-was-interrupted-by-a-call-to-pause-error) and [this](https://developers.google.com/web/updates/2017/06/play-request-was-interrupted) sheds some light on when this could happen. I haven't gone through the web-phone sdk code yet. 

If anyone has any idea about this, please help.

**Comment by vyshakhbabji** [comment]
Thanks for the pr. Will review it tomorrow.

**Comment by vyshakhbabji** [comment]
Duplicate issue:  #131  . Closing this.
