### ISSUE TITLE
Why is sessionId for a call not present in session object?

### ISSUE THREAD

**Issue by mangatinanda** [ringcentral/ringcentral-web-phone#132]
As per my understanding, sessionId is the key by which we can uniquely identify a call. 

In our use case, when the call is in progress, we want to link the call to one of our app entities. 

Since there is no `sessionId` present in the `session object`, we had to do all sorts of workarounds(sadly, none of them are reliable) just to uniquely identify the call. 

Any specific challenge in having the sessionId as part of session object?

**Comment by kirill-konshin** [comment]
`Session` object right now is a slightly patched object of SIPJS. It does not reflect all RC specifics. If there is a demand for `sessionId` I think we can introduce it as a getter or as a field of `Session`.

@vyshakhbabji @anilkumarbp please investigate.

**Comment by embbnux** [comment]
Now, we can get [sipData](https://developer.ringcentral.com/api-docs/latest/index.html#!#SipData) of an active call with `presence?detailedTelephonyState=true&sipData=true`.
But the sipData doesn't match web phone session.  Is is possible to have web phone session id in sipData.

**Comment by embbnux** [comment]
I found that `sessionId` isn't unique for a call. If you call yourself, You can get two active calls with same `sessionId`.

**Comment by salesvue-alex** [comment]
The session id would be very useful!

**Comment by vyshakhbabji** [comment]
The session id would be tracked via /presence api-event filter(via subscription push notification) . Enhancement is a Telephony engineering feature . Will be communicated to the internal team for the backend enhancement. Closing the issue for now. Will be tracked via internal tracking system.
