### ISSUE TITLE
Timeout problem when the call flip.

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-web-phone#133]
I use web phone SDK to flip a number. And found that web phone SDK throws a timeout error. But actually flip number get the call. 
In my opinion, it is better to make `responseTimeout ` as a config. 
https://github.com/ringcentral/ringcentral-web-phone/blob/master/src/ringcentral-web-phone.js#L556

**Comment by kirill-konshin** [comment]
I suggest to change default value instead of passing the config.
