### ISSUE TITLE
error parsing "From" header field

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-web-phone#135]
It reports this error sometime.
error:
```
Tue Aug 22 2017 15:41:15 GMT+0800 (CST) | sip.sipmessage | error parsing "From" header field with value "<sip:#8972010116348137300@104.245.56.83>"
```
all message text:
```
Tue Aug 22 2017 15:41:15 GMT+0800 (CST) | sip.transport | received WebSocket text message:

MESSAGE sip:egtir0hq@ji5cghbihfcu.invalid;transport=ws SIP/2.0
Record-Route: <sip:10.13.122.71:8080;transport=ws;r2=on;lr=on>
Record-Route: <sip:10.13.122.71;r2=on;lr=on>
Via: SIP/2.0/WS  10.13.122.71:8080;branch=z9hG4bKba24.1a8bb7fe75668868a0cc26e9d0485293.0
Via: SIP/2.0/UDP 104.245.56.83:5080;rport=5080;branch=z9hG4bK04Bbf56246c154b483b
From: <sip:#8972010116348137300@104.245.56.83>
To: <sip:to_phone_number@sip.ringcentral.com>
Call-ID: 6665cd676cff804b5cd787dd8a7090ce@10.13.19.179
CSeq: 5888 MESSAGE
Max-Forwards: 67
User-Agent: JEDI/SIP/1.8.0_91
Allow: INVITE,ACK,CANCEL,BYE,REFER,NOTIFY,OPTIONS,MESSAGE
Content-Length:   174
Content-Type: x-rc/agent

<Msg><Hdr SID="" Req="" From="#8972010116348137300@10.13.174.13" To="to_phone_number@sip.ringcentral.com:5060" Cmd="2"/><Bdy Mny="2010407" MB="2147483647" SrvLvl="0"/></Msg>
```

**Comment by vyshakhbabji** [comment]
@embbnux  Can you please attach the full Sip Logs for this issue? I would like to see the REGISTER as well as the state of SIP Session when this error occurs.

**Comment by embbnux** [comment]
Thu Aug 31 2017 15:38:34 GMT+0800 (CST) | sip.transport | received WebSocket text message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS dfnur9sksffd.invalid;branch=z9hG4bK1244158;rport=7410;received=10.13.120.10
To: <sip:18885287464*1302@sip.ringcentral.com>;tag=66d1ae97d02f2b94abe1da3dc56a2cf7-b45d
From: <sip:18885287464*1302@sip.ringcentral.com>;tag=nv3n60oorf
Call-ID: s7mltprdes2pdsdtacacff
CSeq: 85 REGISTER
Contact: <sip:csqdsraj@dfnur9sksffd.invalid;transport=ws>;expires=60
Server: kamailio (4.1.5 (x86_64/linux))
Content-Length: 0

Thu Aug 31 2017 15:39:31 GMT+0800 (CST) | sip.transport | sending WebSocket message:

REGISTER sip:sip.ringcentral.com SIP/2.0
Via: SIP/2.0/WSS dfnur9sksffd.invalid;branch=z9hG4bK9399434
Max-Forwards: 70
To: <sip:18885287464*1302@sip.ringcentral.com>
From: <sip:18885287464*1302@sip.ringcentral.com>;tag=nv3n60oorf
Call-ID: s7mltprdes2pdsdtacacff
CSeq: 86 REGISTER
Authorization: Digest algorithm=MD5, username="15525645020", realm="sip.ringcentral.com", nonce="Wae9rlmnvIKPqJIUtHLJ/8lCc9BGBnmF", uri="sip:sip.ringcentral.com", response="3e2e66412c59fc46e728b241769e8c3f"
P-rc-endpoint-id: 343af282-6e6c-460e-9b55-23658f681269
RC-User-Agent: RingCentral Widget/0.1.0 RCWEBPHONE/0.4.3
Client-id:eac8797af1b3502F2CEAAEECAC3Ed378AA7858A386656f28A008b0c638A754B1
Contact: <sip:csqdsraj@dfnur9sksffd.invalid;transport=ws>;reg-id=1;+sip.instance="<urn:uuid:d363c889-db55-4d86-a733-f5c0ff40213d>";expires=600
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: path, gruu, outbound
User-Agent: SIP.js/0.7.8
Content-Length: 0



LoggerFactory.js:72 Thu Aug 31 2017 15:39:31 GMT+0800 (CST) | sip.transport | received WebSocket text message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS dfnur9sksffd.invalid;branch=z9hG4bK9399434;rport=7410;received=10.13.120.10
To: <sip:18885287464*1302@sip.ringcentral.com>;tag=66d1ae97d02f2b94abe1da3dc56a2cf7-67f5
From: <sip:18885287464*1302@sip.ringcentral.com>;tag=nv3n60oorf
Call-ID: s7mltprdes2pdsdtacacff
CSeq: 86 REGISTER
Contact: <sip:csqdsraj@dfnur9sksffd.invalid;transport=ws>;expires=60
Server: kamailio (4.1.5 (x86_64/linux))
Content-Length: 0



LoggerFactory.js:72 Thu Aug 31 2017 15:39:32 GMT+0800 (CST) | sip.transport | received WebSocket text message:

MESSAGE sip:csqdsraj@dfnur9sksffd.invalid;transport=ws SIP/2.0
Record-Route: <sip:10.13.122.71:8080;transport=ws;r2=on;lr=on>
Record-Route: <sip:10.13.122.71;r2=on;lr=on>
Via: SIP/2.0/WS  10.13.122.71:8080;branch=z9hG4bK701f.b5636f3bff4b3b639d6aea19fef97c26.0
Via: SIP/2.0/UDP 104.245.56.83:5080;rport=5080;branch=z9hG4bK0cB055660f4e1115494
From: <sip:#8972010116348137300@104.245.56.83>
To: <sip:18885287464*1302@sip.ringcentral.com>
Call-ID: 471ff829cc776e80018470ea535b2212@10.13.19.179
CSeq: 30851 MESSAGE
Max-Forwards: 67
User-Agent: JEDI/SIP/1.8.0_91
Allow: INVITE,ACK,CANCEL,BYE,REFER,NOTIFY,OPTIONS,MESSAGE
Content-Length:   165
Content-Type: x-rc/agent

<Msg><Hdr SID="" Req="" From="#8972010116348137300@10.13.174.13" To="18885287464*1302@sip.ringcentral.com:5060" Cmd="1"/><Bdy Cln="" OldMsg="98" NewMsg="102"/></Msg>

LoggerFactory.js:72 Thu Aug 31 2017 15:39:32 GMT+0800 (CST) | sip.sipmessage | error parsing "From" header field with value "<sip:#8972010116348137300@104.245.56.83>"
LoggerFactory.print @ LoggerFactory.js:72
LoggerFactory.(anonymous function) @ LoggerFactory.js:89
Logger.(anonymous function) @ LoggerFactory.js:83
parseHeader @ SIPMessage.js:384
parseHeader @ Parser.js:72
Parser.parseMessage @ Parser.js:236
onMessage @ Transport.js:301
onMessage @ ringcentral-web-phone.js:292
ws.onmessage @ Transport.js:183
LoggerFactory.js:72 Thu Aug 31 2017 15:39:32 GMT+0800 (CST) | sip.parser | error parsing header "From"
LoggerFactory.print @ LoggerFactory.js:72
LoggerFactory.(anonymous function) @ LoggerFactory.js:89
Logger.(anonymous function) @ LoggerFactory.js:83
Parser.parseMessage @ Parser.js:239
onMessage @ Transport.js:301
onMessage @ ringcentral-web-phone.js:292
ws.onmessage @ Transport.js:183
LoggerFactory.js:72 Thu Aug 31 2017 15:39:32 GMT+0800 (CST) | sip.transport | received WebSocket text message:

MESSAGE sip:csqdsraj@dfnur9sksffd.invalid;transport=ws SIP/2.0
Record-Route: <sip:10.13.122.71:8080;transport=ws;r2=on;lr=on>
Record-Route: <sip:10.13.122.71;r2=on;lr=on>
Via: SIP/2.0/WS  10.13.122.71:8080;branch=z9hG4bK67fa.994bb1c512e1f30c4343950f17ab7a8c.0
Via: SIP/2.0/UDP 104.245.56.83:5080;rport=5080;branch=z9hG4bK0cB0555952391ed4c88
From: <sip:#8972010116348137300@104.245.56.83>
To: <sip:18885287464*1302@sip.ringcentral.com>
Call-ID: 26d9f3a66a014d34c0f7703b42fd88f2@10.13.19.179
CSeq: 30852 MESSAGE
Max-Forwards: 67
User-Agent: JEDI/SIP/1.8.0_91
Allow: INVITE,ACK,CANCEL,BYE,REFER,NOTIFY,OPTIONS,MESSAGE
Content-Length:   165
Content-Type: x-rc/agent

<Msg><Hdr SID="" Req="" From="#8972010116348137300@10.13.174.13" To="18885287464*1302@sip.ringcentral.com:5060" Cmd="1"/><Bdy Cln="" OldMsg="98" NewMsg="102"/></Msg>

LoggerFactory.js:72 Thu Aug 31 2017 15:39:32 GMT+0800 (CST) | sip.sipmessage | error parsing "From" header field with value "<sip:#8972010116348137300@104.245.56.83>"
LoggerFactory.print @ LoggerFactory.js:72
LoggerFactory.(anonymous function) @ LoggerFactory.js:89
Logger.(anonymous function) @ LoggerFactory.js:83
parseHeader @ SIPMessage.js:384
parseHeader @ Parser.js:72
Parser.parseMessage @ Parser.js:236
onMessage @ Transport.js:301
onMessage @ ringcentral-web-phone.js:292
ws.onmessage @ Transport.js:183
LoggerFactory.js:72 Thu Aug 31 2017 15:39:32 GMT+0800 (CST) | sip.parser | error parsing header "From"
LoggerFactory.print @ LoggerFactory.js:72
LoggerFactory.(anonymous function) @ LoggerFactory.js:89
Logger.(anonymous function) @ LoggerFactory.js:83
Parser.parseMessage @ Parser.js:239
onMessage @ Transport.js:301
onMessage @ ringcentral-web-phone.js:292
ws.onmessage @ Transport.js:183
LoggerFactory.js:72 Thu Aug 31 2017 15:39:33 GMT+0800 (CST) | sip.transport | received WebSocket text message:

MESSAGE sip:csqdsraj@dfnur9sksffd.invalid;transport=ws SIP/2.0
Record-Route: <sip:10.13.122.71:8080;transport=ws;r2=on;lr=on>
Record-Route: <sip:10.13.122.71;r2=on;lr=on>
Via: SIP/2.0/WS  10.13.122.71:8080;branch=z9hG4bK21dc.795f5fe674b13ffd9ce449bc03e98941.0
Via: SIP/2.0/UDP 104.245.56.83:5080;rport=5080;branch=z9hG4bK0cB0557c23794d2a76d
From: <sip:#8972010116348137300@104.245.56.83>
To: <sip:18885287464*1302@sip.ringcentral.com>
Call-ID: 751cdd9d2ecb3aa1a7c4916a067dca16@10.13.19.179
CSeq: 30854 MESSAGE
Max-Forwards: 67
User-Agent: JEDI/SIP/1.8.0_91
Allow: INVITE,ACK,CANCEL,BYE,REFER,NOTIFY,OPTIONS,MESSAGE
Content-Length:   174
Content-Type: x-rc/agent

<Msg><Hdr SID="" Req="" From="#8972010116348137300@10.13.174.13" To="18885287464*1302@sip.ringcentral.com:5060" Cmd="2"/><Bdy Mny="2960695" MB="2147483647" SrvLvl="0"/></Msg>

LoggerFactory.js:72 Thu Aug 31 2017 15:39:33 GMT+0800 (CST) | sip.sipmessage | error parsing "From" header field with value "<sip:#8972010116348137300@104.245.56.83>"
LoggerFactory.print @ LoggerFactory.js:72
LoggerFactory.(anonymous function) @ LoggerFactory.js:89
Logger.(anonymous function) @ LoggerFactory.js:83
parseHeader @ SIPMessage.js:384
parseHeader @ Parser.js:72
Parser.parseMessage @ Parser.js:236
onMessage @ Transport.js:301
onMessage @ ringcentral-web-phone.js:292
ws.onmessage @ Transport.js:183

**Comment by vyshakhbabji** [comment]
I have created an internal ticket for this - please view your email/glip for further information. Closing this ticket as it doesn't seem like SDK issue.
