### ISSUE TITLE
In firefox browser, Outgoing call popup is display for 5 sec and automatically hide

### ISSUE THREAD

**Issue by viralsasasoftware** [ringcentral/ringcentral-web-phone#136]
I have integrated RingCentral Webphone WebRTC feature in our website. In Firefox browser, Outgoing call popup is display for 5 sec and automatically hide. It’s working fine in Google Chrome.

My Firefox browser details details are here http://www.whatsmybrowser.org/b/TDDQR64
 
FYI, I’m using desktop computer and using headphone for do call.

Can you please help me for solve this  problem?

**Comment by vyshakhbabji** [comment]
@viralsasasoftware  currently we support only Google Chrome browser officially. We are coming out with Firefox official support by end  of this year. We shall keep you updated. 

Can you please attach the debug logs for the session ?
