### ISSUE TITLE
Callee can hear the caller but caller can’t hear  callee

### ISSUE THREAD

**Issue by viralsasasoftware** [ringcentral/ringcentral-web-phone#139]
I have integrated Ringcentral Webphone WebRTC feature in our website. My problem is  Callee can hear the caller but caller can’t hear callee.
 
FYI, I’m using desktop computer and using headphone for do call.

**Comment by vyshakhbabji** [comment]
@viralsasasoftware Please set up your default speakers to headphone - check your speaker settings on your machine. Please attach console logs by setting debug level to 3 and send a mail to devsupport@ringcentral.com for further investigation. This issue is not related to SDK. Closing the case .

**Comment by viralsasasoftware** [comment]
Hello ,

I set Headphone then sdk not allowed me to do call so I set Mic In and its allow me to do call
here is error log of when I set speaker to headphone.
NavigatorUserMediaError {name: "DevicesNotFoundError", message: "", constraintName: ""}constraintName: ""message: ""name: "DevicesNotFoundError"__proto__: NavigatorUserMediaErrorconstraintName: (...)message: (...)name: (...)constructor: ƒ NavigatorUserMediaError()Symbol(Symbol.toStringTag): "NavigatorUserMediaError"get constraintName: ƒ ()get message: ƒ ()get name: ƒ ()__proto__: Object
LoggerFactory.print @ sip-0.7.7.js:2900
LoggerFactory.(anonymous function) @ sip-0.7.7.js:2917
Logger.(anonymous function) @ sip-0.7.7.js:2911
acquireFailed @ sip-0.7.7.js:11174
Promise rejected (async)
getDescription @ sip-0.7.7.js:11167
invite @ sip-0.7.7.js:6486
afterConnected @ sip-0.7.7.js:8847
UA.invite @ sip-0.7.7.js:8866
invite @ ringcentral-web-phone.js:667
makeCall @ custom-rc.js:228
onclick @ therapistAdmin_rc_test.php:1



here is my console log when I set speaker to Mic In.

v=0
o=Sonus_UAC 1824 66208 IN IP4 104.245.56.82
s=SIP Media Capabilities
c=IN IP4 104.245.56.81
t=0 0
m=audio 33012 UDP/TLS/RTP/SAVP 111 126
a=setup:passive
a=fingerprint:sha-256 1D:79:09:D3:E2:C3:E1:AD:28:BF:B1:87:55:65:79:15:02:ED:68:F6:CB:46:BB:D1:BE:B9:44:5B:AF:17:DD:0E
a=ice-ufrag:sioFqAx3
a=ice-pwd:Ib22cSRomdJGouDX+/kdAP3JLevLrntUiOO02X7j
a=candidate:1 1 UDP 2113955071 104.245.56.81 33012 typ host
a=candidate:1 2 UDP 2113955070 104.245.56.81 33013 typ host
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1; maxaveragebitrate=510000
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-15
a=sendrecv
a=maxptime:60


sip-0.7.7.js:2900 Thu Aug 31 2017 10:31:18 GMT+0530 (India Standard Time) | sip.dialog | ovprcap6tmdlu587rb4kdhcvpkq2iegK0c88c244 | new UAC dialog created with status EARLY
sip-0.7.7.js:2900 Thu Aug 31 2017 10:31:18 GMT+0530 (India Standard Time) | sip.dialog | ovprcap6tmdlu587rb4kdhcvpkq2iegK0c88c244 | dialog ovprcap6tmdlu587rb4kdhcvpkq2iegK0c88c244  changed to CONFIRMED state
custom-rc.js:364 Event: Progress
custom-rc.js:400 Event: ICE: iceConnectionChecking
sip-0.7.7.js:2900 Thu Aug 31 2017 10:31:18 GMT+0530 (India Standard Time) | sip.invitecontext.mediahandler | ovprcap6tmdlu587rb4k0egepqnnpm | stream added: default
custom-rc.js:408 Event: ICE: iceCandidate
sip-0.7.7.js:2900 Thu Aug 31 2017 10:31:18 GMT+0530 (India Standard Time) | sip.invitecontext.mediahandler | ovprcap6tmdlu587rb4k0egepqnnpm | RTCIceGatheringState changed: complete
sip-0.7.7.js:2900 Thu Aug 31 2017 10:31:18 GMT+0530 (India Standard Time) | sip.invitecontext.mediahandler | ovprcap6tmdlu587rb4k0egepqnnpm | RTCIceChecking Timeout Triggered after 500 milliseconds
custom-rc.js:401 Event: ICE: iceConnectionConnected
custom-rc.js:402 Event: ICE: iceConnectionCompleted
sip-0.7.7.js:2900 Thu Aug 31 2017 10:31:29 GMT+0530 (India Standard Time) | sip.transport | received WebSocket text message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS ue96c0sr755c.invalid;rport=51996;received=10.13.120.10;branch=z9hG4bK7787127
From: <sip:18186976700*101@sip.ringcentral.com>;tag=dhcvpkq2ie
To: <sip:18184812373@sip.ringcentral.com>;tag=gK0c88c244
Call-ID: ovprcap6tmdlu587rb4k
CSeq: 1120 INVITE
Record-Route: <sip:10.13.120.228:5060;r2=on;lr=on;did=193.db42>
Record-Route: <sip:10.13.120.228:8080;transport=ws;r2=on;lr=on;did=193.db42>
Contact: <sip:18184812373@104.245.56.82:5080>
Allow: INVITE,ACK,CANCEL,BYE,REGISTER,REFER,INFO,SUBSCRIBE,NOTIFY,PRACK,UPDATE,OPTIONS,MESSAGE,PUBLISH
User-Agent: RC_SIPWRP_20.198
Supported: replaces
Content-Length:   651
Content-Disposition: session; handling=required
Content-Type: application/sdp

v=0
o=Sonus_UAC 1824 66208 IN IP4 104.245.56.82
s=SIP Media Capabilities
c=IN IP4 104.245.56.81
t=0 0
m=audio 33012 UDP/TLS/RTP/SAVP 111 126
a=setup:passive
a=fingerprint:sha-256 1D:79:09:D3:E2:C3:E1:AD:28:BF:B1:87:55:65:79:15:02:ED:68:F6:CB:46:BB:D1:BE:B9:44:5B:AF:17:DD:0E
a=ice-ufrag:sioFqAx3
a=ice-pwd:Ib22cSRomdJGouDX+/kdAP3JLevLrntUiOO02X7j
a=candidate:1 1 UDP 2113955071 104.245.56.81 33012 typ host
a=candidate:1 2 UDP 2113955070 104.245.56.81 33013 typ host
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1; maxaveragebitrate=510000
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-15
a=sendrecv
a=maxptime:60


sip-0.7.7.js:2900 Thu Aug 31 2017 10:31:29 GMT+0530 (India Standard Time) | sip.transport | sending WebSocket message:

ACK sip:18184812373@104.245.56.82:5080 SIP/2.0
Route: <sip:10.13.120.228:8080;transport=ws;r2=on;lr=on;did=193.db42>
Route: <sip:10.13.120.228:5060;r2=on;lr=on;did=193.db42>
Via: SIP/2.0/WSS ue96c0sr755c.invalid;branch=z9hG4bK1678207
Max-Forwards: 70
To: <sip:18184812373@sip.ringcentral.com>;tag=gK0c88c244
From: <sip:18186976700*101@sip.ringcentral.com>;tag=dhcvpkq2ie
Call-ID: ovprcap6tmdlu587rb4k
CSeq: 1120 ACK
Supported: outbound
User-Agent: SIP.js/0.7.7
Content-Length: 0



custom-rc.js:363 Event: Accepted
sip-0.7.7.js:2900 Thu Aug 31 2017 10:31:29 GMT+0530 (India Standard Time) | sip.transport | received WebSocket text message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS ue96c0sr755c.invalid;rport=51996;received=10.13.120.10;branch=z9hG4bK7787127
From: <sip:18186976700*101@sip.ringcentral.com>;tag=dhcvpkq2ie
To: <sip:18184812373@sip.ringcentral.com>;tag=gK0c88c244
Call-ID: ovprcap6tmdlu587rb4k
CSeq: 1120 INVITE
Record-Route: <sip:10.13.120.228:5060;r2=on;lr=on;did=193.db42>
Record-Route: <sip:10.13.120.228:8080;transport=ws;r2=on;lr=on;did=193.db42>
Contact: <sip:18184812373@104.245.56.82:5080>
Allow: INVITE,ACK,CANCEL,BYE,REGISTER,REFER,INFO,SUBSCRIBE,NOTIFY,PRACK,UPDATE,OPTIONS,MESSAGE,PUBLISH
User-Agent: RC_SIPWRP_20.198
Supported: replaces
Content-Length:   651
Content-Disposition: session; handling=required
Content-Type: application/sdp

v=0
o=Sonus_UAC 1824 66208 IN IP4 104.245.56.82
s=SIP Media Capabilities
c=IN IP4 104.245.56.81
t=0 0
m=audio 33012 UDP/TLS/RTP/SAVP 111 126
a=setup:passive
a=fingerprint:sha-256 1D:79:09:D3:E2:C3:E1:AD:28:BF:B1:87:55:65:79:15:02:ED:68:F6:CB:46:BB:D1:BE:B9:44:5B:AF:17:DD:0E
a=ice-ufrag:sioFqAx3
a=ice-pwd:Ib22cSRomdJGouDX+/kdAP3JLevLrntUiOO02X7j
a=candidate:1 1 UDP 2113955071 104.245.56.81 33012 typ host
a=candidate:1 2 UDP 2113955070 104.245.56.81 33013 typ host
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1; maxaveragebitrate=510000
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-15
a=sendrecv
a=maxptime:60


sip-0.7.7.js:2900 Thu Aug 31 2017 10:31:29 GMT+0530 (India Standard Time) | sip.transport | sending WebSocket message:

ACK sip:18184812373@104.245.56.82:5080 SIP/2.0
Route: <sip:10.13.120.228:8080;transport=ws;r2=on;lr=on;did=193.db42>
Route: <sip:10.13.120.228:5060;r2=on;lr=on;did=193.db42>
Via: SIP/2.0/WSS ue96c0sr755c.invalid;branch=z9hG4bK8441278
Max-Forwards: 70
To: <sip:18184812373@sip.ringcentral.com>;tag=gK0c88c244
From: <sip:18186976700*101@sip.ringcentral.com>;tag=dhcvpkq2ie
Call-ID: ovprcap6tmdlu587rb4k
CSeq: 1120 ACK
Supported: outbound
User-Agent: SIP.js/0.7.7
Content-Length: 0

**Comment by kirill-konshin** [comment]
@viralsasasoftware please use devsupport@ringcentral.com to resolve this case.

**Comment by viralsasasoftware** [comment]
@kirill-konshin  I have email to devsupport@ringcentral.com but they do not reply till now.
