### ISSUE TITLE
State is not accepted for processing

### ISSUE THREAD

**Issue by YamunaSubramanian** [ringcentral/ringcentral-web-phone#140]
We are getting this error randomly(more often when the system resumes after sleep)

> {code: -4, description: "State is not accepted for processing"} 

in **setRecord** function. Any thoughts on this?

**Comment by vyshakhbabji** [comment]
@YamunaSubramanian  what is the account setup for call recording? Is the extension set to automatic call recording - enabled for the extension/account?  Could you provide full debug log?
