### ISSUE TITLE
Request to support MS IE Edge and UWP apps

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-web-phone#143]
I would like to use RingCentral WebRTC with MS Edge and native Universal Windows Platform (UWP) apps. Both of these support WebRTC:

* [Real-Time Communications on the Universal Windows Platform with WebRTC and ORTC](https://blogs.windows.com/buildingapps/2017/02/22/real-time-communications-universal-windows-platform-webrtc-ortc/#jK5B7F9lOEJ6o83O.97)
* [Is WebRTC ready yet?](http://iswebrtcreadyyet.com)

Let me know when this is supported.

**Comment by vyshakhbabji** [comment]
We are working on stabilizing the webrtc to work with Chrome and Firefox. Chrome is the only browser supported officially. This project is marked as enhancement and will be worked on in future releases of the sdk.

**Comment by JackZong** [comment]
Hi @vyshakhbabji, if the lateset version of webphone SDK support to make WebRTC call with legacy version of edge(non chromium)?

**Comment by tylerlong** [comment]
Closing. New Edge has the same core as Chrome.
