### ISSUE TITLE
Caller unable to here my voice.

### ISSUE THREAD

**Issue by premnathtammina** [ringcentral/ringcentral-web-phone#144]
Hi There,

I have implemented Ringcentral web-phone and made a outbound call. Caller unable to hear my voice and sometimes call goes mute. May i know, why calls are behaving like that?. To replicate this issue i have tested this case with good network connectivity, but still i faced same issue. Caller also connected via different network which is good. Please let me know some cases to fix the issue / guide me to make things work better.

**Comment by kirill-konshin** [comment]
Do you have any issues when you use the demo app?

**Comment by premnathtammina** [comment]
Yes, i  have the same issue when i am using the demo given by you people. 
https://ringcentral-web-phone.herokuapp.com/demo/

**Comment by premnathtammina** [comment]
Hi Kirill,

Is there any update? Please let me know. So we can move to production. Most of the customers facing this issue.

Thanks,
Premnath Tammina

**Comment by kirill-konshin** [comment]
Please contact devsupport@ringcentral.com because seems that it is not an SDK issue, it's something with your configuration/setup.
