### ISSUE TITLE
Upgrade sipjs to 0.9.1

### ISSUE THREAD

**Issue by vyshakhbabji** [ringcentral/ringcentral-web-phone#145]
Issues that we have with the update to 0.9.1:

1. rtcpMuxPolicy: negotiate  
Cannot set rtcpMuxPolicy to negotiate via UA configuration parameter
https://github.com/onsip/SIP.js/issues/476

2. hackStripTcp:true
Cannot strip tcp candidates via UA configuration parameter 

3.  Need to figure out how to handle Early Media SIP '183'

```
session.on('progress', function(incomingResponse) {
            if (incomingResponse.status_code === 183 && incomingResponse.body) {
                session.createDialog(incomingResponse, 'UAC');
                session.sessionDescriptionHandler.setDescription(incomingResponse).then(function() {
                    session.status = 11; //C.STATUS_EARLY_MEDIA;
                    session.hasAnswer = true;
                });
            }
        });
```
throws: 
Failed to parse SessionDescription. SIP/2.0 183 Session Progress Expect line: v=

**Comment by embbnux** [comment]
@vyshakhbabji When will we get this implemented? Some API used by sip.js 0.7 will be deprecated soon by chrome.

**Comment by kirill-konshin** [comment]
Updated to 0.10.0
