### ISSUE TITLE
Subscription Is Not Listening

### ISSUE THREAD

**Issue by zubair1103** [ringcentral/ringcentral-web-phone#151]
I registered a subscription using following code. Subscription is registered successfully but it never triggers the event `subscription.events.notification`. SIP log is attached as well [sip-log.txt](https://github.com/ringcentral/ringcentral-web-phone/files/1770553/sip-log.txt).

`var subscription = sdk.createSubscription();
subscription.addEventFilters('/account/~/extension/~/presence?detailedTelephonyState=true');
subscription.on(subscription.events.notification, function (msg) {
	console.log("MESSAGE", msg);
});
subscription.register().then(function (response) {
	console.log('Success: RC Subscription is listening', response);
}).catch (function (e) {
	console.error('RC Subscription Error: ' + e.message);
});
`

**Comment by vyshakhbabji** [comment]
Not Webphone SDK issue. Moved to support queue.
