### ISSUE TITLE
unable to perform calling on online demo web phone

### ISSUE THREAD

**Issue by Ganesh-kvk** [ringcentral/ringcentral-web-phone#153]
Hi,

   I want to implement Ringcetral web phone to our web app, i am trying to use the demo web phone to see how it works, but after giving app key & secret in next page phone number given to make call, i got the popup but it was closed automatically. 
Can you please tell me on how to check demo web phone online.

[Online demo referring link](https://ringcentral-web-phone.herokuapp.com/demo)
I am getting following error in console chrome browser(v 65.0)
![web phone demo error](https://user-images.githubusercontent.com/12134203/38241742-a0b48400-3750-11e8-82bb-b30879bb284f.PNG)

**Comment by vyshakhbabji** [comment]
Please check the permission for microphone device and speakers on the browser. Set the permissions to "Always Allow" for webphone instance.
