### ISSUE TITLE
after clicked Authorization Code button and got auth, I get some errors

### ISSUE THREAD

**Issue by hawx1993** [ringcentral/ringcentral-web-phone#154]
I clone this repo,and run this demo. After I clicked Authorization Code button,I get this errors:

show below:

![wechatimg31](https://user-images.githubusercontent.com/5305263/38488669-c3adf7fa-3c16-11e8-8b00-7a49643a42e2.jpeg)

I click first errors:

```js
{
  "errorCode" : "InsufficientPermissions",
  "message" : "In order to call this API endpoint, application needs to have [ReadAccounts] permission",
  "errors" : [ {
    "errorCode" : "CMN-401",
    "message" : "In order to call this API endpoint, application needs to have [ReadAccounts] permission",
    "permissionName" : "ReadAccounts"
  } ],
  "permissionName" : "ReadAccounts"
}
```

help!!!

**Comment by kirill-konshin** [comment]
Please write an email to devsupport@ringcentral.com they will help you to configure your app properly.
