### ISSUE TITLE
Sleep computer dose not disconnect connection

### ISSUE THREAD

**Issue by ruleechen** [ringcentral/ringcentral-web-phone#161]
Web phone connection seems not disconnect after sleep computer. The only happens on sleeping for a little while and then resume. Maybe less than 1 minute. It works correctly if sleep computer for some minutes.

Environment:
- windows 10
- ringcentral-web-phone: 0.4.5

Steps to reproduce:
1. Login web phone and sleep computer.
2. Make a call to the logged in user from another device and then hang up the call.
3. Resume the computer.
4. Then the hanged up call will keep ringing.

**Comment by vyshakhbabji** [comment]
This is not a SDK related issue. The machine/browser/application might still be logged in  or keeps the registrations active and hence the issue. Please keep a logged running to check if the registration is still active when the computer is put to sleep.

**Comment by ruleechen** [comment]
@vyshakhbabji 
Ok. Thank you!
Will subscribe to the system events for handling the web phone connection.
