### ISSUE TITLE
Answer SDP without a=mid is rejected . Issue with >=Chrome v72 

### ISSUE THREAD

**Issue by vyshakhbabji** [ringcentral/ringcentral-web-phone#174]
There is an ongoing changes to the SDP standards and I have found out a bug which is being worked on by google chrome and FF developers. The SDPs without   a=mid is rejected with an error . 

'''DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer. '''

For further info , please check the link below. 

https://bugs.chromium.org/p/chromium/issues/detail?id=901787&can=1&q=sdp&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

https://bugzilla.mozilla.org/show_bug.cgi?id=1495569

https://groups.google.com/forum/#!topic/sip_js/HB44b-y0Afs

https://bugs.chromium.org/p/chromium/issues/detail?id=892706&can=1&q=sdp&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

Precautions to be taken by the developers of this SDK: 
1. Upgrade to the latest webphone SDK
2. Please watch this issue. 

We have a solution for this issue, it will be part of future releases.
Old versions of SDK might not be compatible. Please upgrade to the latest release of the SDK. We will be releasing the new version of the SDK to fix the issue with chrome v72  stable release.

**Comment by walltex** [comment]
It seems it is became actual starring from v71.

**Comment by vyshakhbabji** [comment]
@walltex  can you provide me the link for chrome v71 bug ?

**Comment by vyshakhbabji** [comment]
Quick fix in case you hit [this ](https://github.com/ringcentral/ringcentral-web-phone/issues/174#issue-382443629) error while testing on > chrome v71 : 

If you are using : webRTC SDK > 0.4.X ,  the fix would be to add this piece of code in the webphone SDK under the function patchSession(session) 

replace 

   ```
 session.on('progress', function(incomingResponse) {
            stopPlaying();
            if (incomingResponse.status_code === 183 && incomingResponse.body) {
                session.createDialog(incomingResponse, 'UAC');
                session.sessionDescriptionHandler.setDescription(incomingResponse.body).then(function() {
                    session.status = 11; //C.STATUS_EARLY_MEDIA;
                    session.hasAnswer = true;
                });
            }
        });
```

with

```
        session.on('progress', function(incomingResponse) {
            stopPlaying();
            if (incomingResponse.status_code === 183 && incomingResponse.body) {
                var sdp = incomingResponse.body;
                if (sdp.search(/^a=mid.*$/gm) === -1) {
                    var mlines_1 = sdp.match(/^m=.*$/gm);
                    sdp = sdp.split(/^m=.*$/gm);
                    mlines_1.forEach(function (elem, idx) {
                        mlines_1[idx] = elem + '\na=mid:' + idx;
                    });
                    sdp.forEach(function (elem, idx) {
                        if (mlines_1[idx]) {
                            sdp[idx] = elem + mlines_1[idx];
                        }
                    });
                    sdp = sdp.join('');
                    // description.sdp = sdp;
                }
                session.createDialog(incomingResponse, 'UAC');
                session.sessionDescriptionHandler.setDescription(incomingResponse.body).then(function() {
                    session.status = 11; //C.STATUS_EARLY_MEDIA;
                    session.hasAnswer = true;
                });
            }
        });
```

Please watch this issue for the changes for the SDK itself in the next release. Please prepare for the upgrade of the webRTC sdk to the latest SDK release.
