### ISSUE TITLE
response var  is not defined in catch on the line 414

### ISSUE THREAD

**Issue by Alex-us** [ringcentral/ringcentral-web-phone#179]
response is not defined here: 
https://github.com/ringcentral/ringcentral-web-phone/blob/515b4adb35845201ba3826b8cfdf24028e10c394/src/ringcentral-web-phone.js#L414

Also, why you fail session and then terminate it? Just fail is not enough?

**Comment by vyshakhbabji** [comment]
will be fixed in next release
