### ISSUE TITLE
Hold/ unhold doesnt work on Firefox 

### ISSUE THREAD

**Issue by vyshakhbabji** [ringcentral/ringcentral-web-phone#182]
This issue is because we are setting the SDP semantics to plan b and it is related to this issue : https://github.com/sipwise/rtpengine/issues/641 

We already have a fix for this but is not a part of SDK as we are waiting on the majority of our users to move to >= Chrome v72

**Comment by tylerlong** [comment]
version 2.0 doesn't have this issue
