### ISSUE TITLE
Webphone Registration/Network Recovery issue 

### ISSUE THREAD

**Issue by vyshakhbabji** [ringcentral/ringcentral-web-phone#184]
Webphone SDK should be able to recover the network state change (wifi - no network - wifi) , (wifi -> no network -> 4g), media server recovery.

Things to do : 

1. Change default values to below parameters: 
    ```
      maxReconnectionAttempts: options.maxReconnectionAttempts || 3,
      reconnectionTimeout: options.reconnectionTimeout || 5,
      connectionTimeout: options.connectionTimeout || 5
    ```

2.  Add secondary proxy server to `wsservers`

3.  Client should design the app to recover by reprovisioning the webphone object when the above 2 fixes  fail

**Comment by kirill-konshin** [comment]
Some thoughts on the implementation:

1. Create a method on `WebPhone` instances, say `reprovision(regData)` and feed this data to `webPhone.ua` instance (which return a promise)
2. Add an example to README which will use any of the appropriate existing events like so:
```js
webPhone.ua.on('registration-failed', function(){
  platform
  .post('/client-info/sip-provision', {sipInfo: [{transport: 'WSS'}]})
  .then(function (res) {
    return webPhone.reprovision(res.json());
  });
});
```

**Comment by vyshakhbabji** [comment]
For v 0.7.0 , to prevent the clients from falling back to the secondary backup proxy sooner than the ~90s, I am currently going to introduce a delay of at least 3 min -  10 attempts of random incremental reconnection timeout ( not more than 240s ) for primary outbound proxy. This will give sufficient time for the backend to recover. Also, it gives the client  10 attempts to connect to primary o/p and if the client fails to recover on primary, it can fall back to secondary o/p following the same rule. If both the situation fails, the client can either choose to check primary / secondary pair one more time or go through fresh sip-provisioning to see if it can get new pairs of primary and secondary. 

In case, the client is connected to backup, the client has to switch back to the primary proxy within a certain interval.
