### ISSUE TITLE
Inital loading of sipjs with webphone throws below warning

### ISSUE THREAD

**Issue by vyshakhbabji** [ringcentral/ringcentral-web-phone#191]
`
Wed Feb 13 2019 16:14:28 GMT-0800 (Pacific Standard Time) | sip.transport | Tried to assert STATUS_OPEN but is currently STATUS_CONNECTING
Wed Feb 13 2019 16:14:28 GMT-0800 (Pacific Standard Time) | sip.transport | Transport error: unable to send message - WebSocket not open
`

Tracking: https://github.com/onsip/SIP.js/issues/558

**Comment by Alex-us** [comment]
This is because userAgent.start() has async inside but userAgent.register(); execution is sync right after start() execution. So we have a situation when socket is not open yet, but we already trying to register

**Comment by Alex-us** [comment]
Fix included into #198

**Comment by Alex-us** [comment]
@kirill-konshin  please close, it is fixed in 0.7.0
