### ISSUE TITLE
The demo stays on the blank web page after the "Authorize" button is hit

### ISSUE THREAD

**Issue by eliassun** [ringcentral/ringcentral-web-phone#195]
The demo of the latest master branch will stay on the blank webpage after the "Authorize" button is hit.  Steps to reproduce:
1. Login with the developer account.
2. Hit the "Authorize" button 
Results: The web page stays on "http://127.0.0.1:8080/demo/callback" forever.

**Comment by kirill-konshin** [comment]
Fixed
