### ISSUE TITLE
onTransportReceiveMsg is not used

### ISSUE THREAD

**Issue by Alex-us** [ringcentral/ringcentral-web-phone#199]
onTransportReceiveMsg  is obsolete and can be cleaned out. (It is also not used for some time due to bug inside)  

`function onTransportReceiveMsg(this: WebPhoneUserAgent, e: any): any {
    // This is a temporary solution to avoid timeout errors for MESSAGE responses.
    // Timeout is caused by port specification in host field within Via header.
    // sip.js requires received viaHost in a response to be the same as ours via host therefore
    // messages with the same host but with port are ignored.
    // This is the exact case for WSX: it send host:port inn via header in MESSAGE responses.
    // To overcome this, we will preprocess MESSAGE messages and remove port from viaHost field.
    var data = e.data;

    // WebSocket binary message.
    if (typeof data !== 'string') {
        try {
            data = String.fromCharCode.apply(null, new Uint8Array(data));
        } catch (error) {
            return this.__onTransportReceiveMsg.call(this, e);
        }
    }

    if (data.match(/CSeq:\s*\d+\s+MESSAGE/i)) {
        const re = new RegExp(this.configuration.viaHost + ':\\d+', 'g');
        const newData = e.data.replace(re, this.configuration.viaHost);
        Object.defineProperty(e, 'data', {
            value: newData,
            writable: false
        });
    }

    return this.__onTransportReceiveMsg.call(this, e);
}`

**Comment by kirill-konshin** [comment]
Also feel free to remove in your PR #198

**Comment by Alex-us** [comment]
Fix included into #198
