### ISSUE TITLE
Cannot mute/unmute calls

### ISSUE THREAD

**Issue by Alex-us** [ringcentral/ringcentral-web-phone#200]
There is no more STATUS_CONNECTED for the session, use Session.C.STATUS_CONFIRMED

`/*--------------------------------------------------------------------------------------------------------------------*/
function mute(this: WebPhoneSession, silent?: boolean): void {
    if (this.status !== Session.C.STATUS_CONFIRMED) {
        this.logger.warn('An acitve call is required to mute audio');
        return;
    }
    this.logger.log('Muting Audio');
    if (!silent) {
        this.emit('muted', this);
    }
    return toggleMute(this, true);
}

/*--------------------------------------------------------------------------------------------------------------------*/

function unmute(this: WebPhoneSession, silent?: boolean): void {
    if (this.status !== Session.C.STATUS_CONFIRMED) {
        this.logger.warn('An active call is required to unmute audio');
        return;
    }
    this.logger.log('Unmuting Audio');
    if (!silent) {
        this.emit('unmuted', this);
    }
    return toggleMute(this, false);
}`

**Comment by kirill-konshin** [comment]
You can include this in your #198 pull request

**Comment by Alex-us** [comment]
Fix included into #198
