### ISSUE TITLE
onHold function returns undefined

### ISSUE THREAD

**Issue by vyshakhbabji** [ringcentral/ringcentral-web-phone#221]
Fixed by changing 

function onLocalHold(this: WebPhoneSession): boolean {
    return this.local_hold;
}

to

function onLocalHold(this: WebPhoneSession): boolean {
    return this.localHold;
}

replace this.local_hold with this.localHold;

**Comment by dougroutledge** [comment]
You also cannot place a call on hold, it returns an error saying it is already on hold.  Changing the 3 instances does not fix it.

**Comment by dougroutledge** [comment]
Nevermind, I found it.  It appears you also changed the session variable from local_hold to localHold too, so anyone using that to determine if the call is already on hold will need to update that as well.

**Comment by kirill-konshin** [comment]
Yep, as described in the upper section.
