### ISSUE TITLE
Reconnection attempts when the client is on secondary backup proxy  will not attempt to connect to primary proxy 

### ISSUE THREAD

**Issue by vyshakhbabji** [ringcentral/ringcentral-web-phone#225]
Let's say the instance (Client) is on the secondary(backup) o/b proxy for some reason.

When the Reconnection attempts happen, the client attempts to reconnect only 10 times on secondary outbound proxy and it will not attempt switching to the primary.  The client will close the websocket connection going to the closed state. 

The problem: Until the client is not on the primary or switch back hasn't happened,  the client gets only  10 attempts ( 3:30 min) to connect back.

**Comment by vyshakhbabji** [comment]
@Alex-us  how do u want to handle this issue ?

**Comment by Alex-us** [comment]
This is actually not a bug. On the Glip side (let's say client) we handle closed state of transport and destroy Webphone object showing telephony not available status. Then after some timeout we try to initialize web-phone from the scratch. This is how it works now

**Comment by Alex-us** [comment]
If we want to  move all these func to web-phone, it will require some work on Glip side to allow webphone to handle this

**Comment by vyshakhbabji** [comment]
I will write down this in doc for clients to handle this scenario in a similar way.
