### ISSUE TITLE
On Closed State reset switchbackproxy timer 

### ISSUE THREAD

**Issue by vyshakhbabji** [ringcentral/ringcentral-web-phone#226]
LoggerFactory.js:88 Fri Jun 14 2019 15:26:04 GMT-0700 (Pacific Daylight Time) | sip.transport | attempted to get next ws server but there are no available ws servers left
e.print @ LoggerFactory.js:88
e.genericLog @ LoggerFactory.js:73
e.genericLog @ LoggerFactory.js:106
e.warn @ LoggerFactory.js:102
r.getNextWsServer @ Transport.js:374
(anonymous) @ sipTransportConstructor.ts:134
step @ session.ts:703
(anonymous) @ session.ts:703
(anonymous) @ session.ts:703
./src/sipTransportConstructor.ts.__awaiter @ session.ts:703
reconnect @ sipTransportConstructor.ts:90
r.onClose @ Transport.js:289
15:26:04.676 LoggerFactory.js:88 Fri Jun 14 2019 15:26:04 GMT-0700 (Pacific Daylight Time) | sip.transport | no available ws servers left - going to closed state
e.print @ LoggerFactory.js:88
e.genericLog @ LoggerFactory.js:73
e.genericLog @ LoggerFactory.js:106
e.warn @ LoggerFactory.js:102
(anonymous) @ sipTransportConstructor.ts:105
step @ session.ts:703
(anonymous) @ session.ts:703
(anonymous) @ session.ts:703
./src/sipTransportConstructor.ts.__awaiter @ session.ts:703
reconnect @ sipTransportConstructor.ts:90
(anonymous) @ sipTransportConstructor.ts:136
step @ session.ts:703
(anonymous) @ session.ts:703
(anonymous) @ session.ts:703
./src/sipTransportConstructor.ts.__awaiter @ session.ts:703
reconnect @ sipTransportConstructor.ts:90
r.onClose @ Transport.js:289
15:26:04.677 index.js:189 WebSocket closed.
15:27:35.565 index.js:185 switching back to primary outbound proxy
15:27:35.565 LoggerFactory.js:88 Fri Jun 14 2019 15:27:35 GMT-0700 (Pacific Daylight Time) | sip.transport | forcing connect to main WS server
15:27:35.581 LoggerFactory.js:88 Fri Jun 14 2019 15:27:35 GMT-0700 (Pacific Daylight Time) | sip.transport | Attempting to transition status from 3 to 2
15:27:35.582 LoggerFactory.js:88 Fri Jun 14 2019 15:27:35 GMT-0700 (Pacific Daylight Time) | sip.transport | Attempted to assert 3 as 1- continuing with option: 'force'
e.print @ LoggerFactory.js:88
e.genericLog @ LoggerFactory.js:73
e.genericLog @ LoggerFactory.js:106
e.warn @ LoggerFactory.js:102
r.statusAssert @ Transport.js:475
r.statusTransition @ Transport.js:501
r.disconnectPromise @ Transport.js:95
t.disconnect @ Transport.js:75
(anonymous) @ sipTransportConstructor.ts:97
step @ session.ts:703
(anonymous) @ session.ts:703
(anonymous) @ session.ts:703
./src/sipTransportConstructor.ts.__awaiter @ session.ts:703
reconnect @ sipTransportConstructor.ts:90
(anonymous) @ index.js:186
a.emit @ events.js:146
(anonymous) @ sipTransportConstructor.ts:177
setTimeout (async)
scheduleSwitchBackMainProxy @ sipTransportConstructor.ts:174
__onConnectedToBackup @ sipTransportConstructor.ts:211
__afterWSConnected @ sipTransportConstructor.ts:216
a.emit @ events.js:151
r.onOpen @ Transport.js:237
15:27:35.582 Transport.js:117 Uncaught (in promise) TypeError: Cannot read property 'wsUri' of undefined
    at Transport.js:117
    at new Promise (<anonymous>)
    at r.disconnectPromise (Transport.js:109)
    at r.t.disconnect (Transport.js:75)
    at r.<anonymous> (sipTransportConstructor.ts:97)
    at step (session.ts:703)
    at Object.next (session.ts:703)
    at session.ts:703
    at new Promise (<anonymous>)
    at ./src/sipTransportConstructor.ts.__awaiter (session.ts:703)
(anonymous) @ Transport.js:117
r.disconnectPromise @ Transport.js:109
t.disconnect @ Transport.js:75
(anonymous) @ sipTransportConstructor.ts:97
step @ session.ts:703
(anonymous) @ session.ts:703
(anonymous) @ session.ts:703
./src/sipTransportConstructor.ts.__awaiter @ session.ts:703
reconnect @ sipTransportConstructor.ts:90
(anonymous) @ index.js:186
a.emit @ events.js:146
(anonymous) @ sipTransportConstructor.ts:177
Promise.then (async)
step @ session.ts:703
(anonymous) @ session.ts:703
./src/sipTransportConstructor.ts.__awaiter @ session.ts:703
reconnect @ sipTransportConstructor.ts:90
(anonymous) @ index.js:186
a.emit @ events.js:146
(anonymous) @ sipTransportConstructor.ts:177
setTimeout (async)
scheduleSwitchBackMainProxy @ sipTransportConstructor.ts:174
__onConnectedToBackup @ sipTransportConstructor.ts:211
__afterWSConnected @ sipTransportConstructor.ts:216
a.emit @ events.js:151
r.onOpen @ Transport.js:237

**Comment by vyshakhbabji** [comment]
if (this.noAvailableServers()) {
        this.logger.warn('no available ws servers left - going to closed state');
        this.status = C.STATUS_CLOSED;
        this.emit('closed');
        this.resetServerErrorStatus();
        clearTimeout(mainProxy.switchBackTimer);
        return;
    }

**Comment by vyshakhbabji** [comment]
```
function __onConnectedToMain(this: WebPhoneSIPTransport): void {
    const mainProxy = this.configuration.wsServers[0];

    if (mainProxy.switchBackTimer) {
        clearTimeout(mainProxy.switchBackTimer);
        mainProxy.switchBackTimer = null;
    }
}
```


There is no context for `mainProxy.switchBackTimer` as this param is not global.

**Comment by vyshakhbabji** [comment]
@Alex-us  pls review the fix for this here : https://github.com/vyshakhbabji/web-phone-1/blob/master/src/sipTransportConstructor.ts

**Comment by Alex-us** [comment]
I think this will not fix the issue, since on transport close state GLIP destroys web-phone and other client might do nothing and will catch it.  
Please see  https://github.com/vyshakhbabji/web-phone-1/pull/14
