### ISSUE TITLE
If the switchback is not done when there are no active sessions , there exists one way audio issue on active call

### ISSUE THREAD

**Issue by vyshakhbabji** [ringcentral/ringcentral-web-phone#227]
Solution: don't allow switchback to trigger reconnect when there is an active session. 

Enhancement:  reconnect media after switchback

**Comment by Alex-us** [comment]
This currently implemented on Glip side. I have a plan to move this to Web-phone both: 
1. reconnect to main shoulb be handeled by Web-phone
2. No reconnect if any active session  and schedule reconnection after call end;

**Comment by vyshakhbabji** [comment]
Related to #185
