### ISSUE TITLE
Sometime closing websocket taking too long

### ISSUE THREAD

**Issue by Alex-us** [ringcentral/ringcentral-web-phone#230]
sip.js transport handling is based on 'closed', 'open' event fired by browser websocket. Sometimes these events working not as expected (for the cases of disconnecting and connecting). 
This causing long delays (sometimes even infinite) on closing the websocket and waiting for the 'close' event. 
The idea of improvement is that in case of forcing disconnection do not wait for events, but destroy socket and cleanup listeners 'manually' by some timeout (we can use already existing connectionTimeout parameter or do not use timeout at all and destroy immediately)

**Comment by vyshakhbabji** [comment]
@Alex-us  please close this issue if you dont see this issue anymore.
