### ISSUE TITLE
Session information on parked call pickup

### ISSUE THREAD

**Issue by dougroutledge** [ringcentral/ringcentral-web-phone#231]
Rather than showing for example *801 undefined for call picked out of the parking lot, the session should contain the original caller ID once the call is connected.

**Comment by vyshakhbabji** [comment]
Hi @dougroutledge ,  using the call session notification apis via subscription will provide you all the caller / callee information and the state of call.

**Comment by dougroutledge** [comment]
So we need to burn API calls, and maintain 2 copies of the user session to get accurate caller ID?  Yikes.

**Comment by dougroutledge** [comment]
Captured the telephony session information, it is incorrect here as well
to party shows the park number, from party shows the users DID number.

**Comment by tylerlong** [comment]
I am not what the SDK can do to improve this situation. Since the SDK is meant to be client side library without server side (it does talk to SIP server but it cannot use the SIP server as a database to freely save/retrieve data).

Let say agent A parked a call at 801, in theory, this SDK can save the call session information on localStorage. But what if agent B picked up the call? There is no way for the SDK to forward any information to agent B.

I am open to ideas. Please let me know what the SDK can do to improve the situation. @dougroutledge

**Comment by tylerlong** [comment]
> This is 5 years old...

Yes. Just going through every open ticket.  Please let me know if it's OK to close it. Thanks.

**Comment by tylerlong** [comment]
After investigation, I conclude that it is impossible to do it within this SDK.
I would suggest app to do it instead. Before app parks a call, it knows the call session information, after the call is parked, the app gets the parked location, like 801/802...etc.  
The app could use the park location as key, save the call session information to some quick cache server (like Redis). Set the data to expire in 5 minutes (call park by default expires in 5 minutes).
Every app instance could check this quick cache server to know the current parked calls and their original session information.

But I think RingCentral could provide such an API, to provide a list of all the parked calls together with their original session information. I will submit an internal feature quest, but I am not sure it will be addressed.

**Comment by tylerlong** [comment]
> But I think RingCentral could provide such an API, to provide a list of all the parked calls together with their original session information. I will submit an internal feature quest, but I am not sure it will be addressed.

The internal ticket was closed. They will not do it. 
There is not much that this SDK can do.
