### ISSUE TITLE
pdfs are not found

### ISSUE THREAD

**Issue by Archer-Thane** [ringcentral/ringcentral-web-phone#281]
File not found."

**Comment by kirill-konshin** [comment]
Need more information.

**Comment by Archer-Thane** [comment]
when I click on the pdfs offered in readme.md, servers shows that File not found and not passing by pdfs.
There are two pdfs inside readme, about networking.
🙏

**Comment by kirill-konshin** [comment]
@vyshakhbabji please take care of this.

**Comment by vyshakhbabji** [comment]
Will need to update the  Readme's networking doc with the links here :

https://support.ringcentral.com/s/article/9233?language=en_US
https://netstorage.ringcentral.com/documents/sip.pdf

**Comment by vyshakhbabji** [comment]
@kirill-konshin  will change it in place in some time
