### ISSUE TITLE
The audio not recycled after ringing

### ISSUE THREAD

**Issue by linjunpop** [ringcentral/ringcentral-web-phone#284]
The audio is still playable after the incoming phone call is ended.

Screenshot:

<img width="497" alt="image" src="https://user-images.githubusercontent.com/214616/79708118-23593700-82f1-11ea-82b4-37c9c05d66a0.png">

Tested on:

Chrome: Version 80.0.3987.163 (Official Build) (64-bit)
RingCentral for Google: https://chrome.google.com/webstore/detail/ringcentral-for-google/fddhonoimfhgiopglkiokmofecgdiedb v4.2.10

**Comment by kirill-konshin** [comment]
I'm not sure this is the right repo for this kind of bug. @vyshakhbabji @tylerlong please take a look.

**Comment by vyshakhbabji** [comment]
@linjunpop  Please open this issue in Google Chrome Extension / Emveddable Repo. @embbnux  please look into this and lemme know if you need my attention

**Comment by embbnux** [comment]
We need to refactor AudioHelper to remove audio element when ringing and outgoing audio is not playing.

**Comment by tylerlong** [comment]
Version 2.0 doesn't play ringing audio at all. The SDK only issues call ringing and disposed event. 
It's up to client app to play ringing audio. Client app may choose to play it or not.  It controls when to play and stop it.
