### ISSUE TITLE
Feature Request: Park Pickup

### ISSUE THREAD

**Issue by dougroutledge** [ringcentral/ringcentral-web-phone#289]
Being able to pickup a parked call and retain the caller information would be valuable.  You can dial *8Xx to get the call back, but you lose the caller id information on the call going forward.

**Comment by tylerlong** [comment]
This one is related to https://github.com/ringcentral/ringcentral-web-phone/issues/231
Although both are quite old.

**Comment by tylerlong** [comment]
Closing, please refer to https://github.com/ringcentral/ringcentral-web-phone/issues/231
