### ISSUE TITLE
index.js:1 Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by JSGund** [ringcentral/ringcentral-web-phone#290]
I have cloned this sample and have the required details but once I started 'npm start', I am getting below error:

![image](https://user-images.githubusercontent.com/14850263/85973318-fb243d80-b9ef-11ea-88a2-7eb533c98522.png)

Let me know, how to fix this issue? so I can run demo.

Thanks in advance, Jeetendra

**Comment by kirill-konshin** [comment]
Which version are you using?

**Comment by JSGund** [comment]
I have cloned the latest code from this sample and trying to run the app but catch by the above error.

**Comment by JSGund** [comment]
I had the same steps again and its running now, thanks.
