### ISSUE TITLE
Dialing *8xx loses caller id of parked caller

### ISSUE THREAD

**Issue by dougroutledge** [ringcentral/ringcentral-web-phone#296]
Since there is no park pickup a webRTC user must dial *8xx to unpark a call.  Doing so the webRTC sessions loses the callerid and only displays *8xx going forward.

**Comment by tylerlong** [comment]
Related to https://github.com/ringcentral/ringcentral-web-phone/issues/231

**Comment by tylerlong** [comment]
Closing. Please refer to https://github.com/ringcentral/ringcentral-web-phone/issues/231
