### ISSUE TITLE
Feature : Return parties and telephonySessionId in sessions

### ISSUE THREAD

**Issue by dougroutledge** [ringcentral/ringcentral-web-phone#299]
This API needs to return data that would allow developers to match up session with the telephony sessions of the call control api.

**Comment by tylerlong** [comment]
This feature is availabe in version 2: https://github.com/ringcentral/ringcentral-web-phone/blob/fb1256e61894d11eaea437f973231a04995e15a8/src/call-session/index.ts#L46-L52

You just use the following code to access them:

```ts
callSession.sessionId; // same as call control api telephonySessionId
callSession.partyId; // same as call control api partyId
```
