### ISSUE TITLE
Hold fails on outbound call

### ISSUE THREAD

**Issue by dougroutledge** [ringcentral/ringcentral-web-phone#305]
If you make an outbound call, the party answers, you cannot put the call on hold, the web-phone sdk throws an error "Hold could not be completed"

**Comment by vyshakhbabji** [comment]
My tests worked fine for hold. Can you please confirm if this issue still persists for you ? If not i will close this issue.

**Comment by dougroutledge** [comment]
no the issue persists 100% of the time on an outbound call.  session.hold() fails.

Uncaught (in promise) Error: Hold could not be completed
    at t.<anonymous> (webphone.js:1)

**Comment by tylerlong** [comment]
I believe this has been fixed long ago. Test 2.0, no such issue.
