### ISSUE TITLE
Should not resolve transfer action if server not responses "notify" with 200 OK. 

### ISSUE THREAD

**Issue by jayson-zhang-RC** [ringcentral/ringcentral-web-phone#330]
Some features like "transfer", base on the SIP "REFER" message, should wait "NOTIFY" message to get its result. But there is not a good way to get the result from webphone. That will make the client can't get the server's response correctly and do property actions.

**Comment by tylerlong** [comment]
Not an issue for 2.0: https://github.com/ringcentral/ringcentral-web-phone/blob/fb1256e61894d11eaea437f973231a04995e15a8/src/call-session/index.ts#L288
