### ISSUE TITLE
Should reject the promise if call `reconnectMedia` function failed due to the `self.session` is empty.

### ISSUE THREAD

**Issue by jayson-zhang-RC** [ringcentral/ringcentral-web-phone#331]
![image](https://user-images.githubusercontent.com/81540602/121456898-5d940500-c9d9-11eb-880a-a9fbddc0d06a.png)

Should reject the promise if call `reconnectMedia` function failed due to the `self.session` is empty.

**Comment by tylerlong** [comment]
What is the point of `reconnectMedia`? I read source code and I think it is very hacky. 
We have released 2.0 today. Feel free to test and report.

**Comment by tylerlong** [comment]
I think this is probably part of re-INVITE.  When network changes (like from WiFi to cellular), you will have to re-INVITE with new SDP. Supported in latest version of SDK. Please refer to README.
