### ISSUE TITLE
Support to change device for ringing audio

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-web-phone#335]
Now we have audioHelper to please incoming and outgoing audio https://github.com/ringcentral/ringcentral-web-phone/blob/master/src/audioHelper.ts
Need to add interface to support set output device.

**Comment by embbnux** [comment]
link https://github.com/ringcentral/ringcentral-embeddable/issues/559

**Comment by tylerlong** [comment]
Version 2 doesn't play ringing audio.
