### ISSUE TITLE
Caller can't get voice when user receive a incoming call at ipadOS 15.x Safari

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-web-phone#341]
At ipadOS 15.1 and 15.2, when user receives a incoming call with web phone sdk, user can hear caller's voice, but caller can't hear about the user.

link https://github.com/ringcentral/ringcentral-embeddable/issues/580

**Comment by tylerlong** [comment]
Test version 2.0 and see if you can reproduce it.

**Comment by tylerlong** [comment]
Tested on my iPhone with Safari browser, it worked without any issue.
