### ISSUE TITLE
Please use @ringcentral/sdk package as ringcentral package is now deprecated

### ISSUE THREAD

**Issue by grandmastersoftware** [ringcentral/ringcentral-web-phone#343]
Hi, we are using this wonderful sample in our implementation.

I just noticed the included ringcentral npm package is deprecated.
https://www.npmjs.com/package/ringcentral

There's a new one.
https://www.npmjs.com/package/@ringcentral/sdk

Any plans for an update?

Thanks

**Comment by tylerlong** [comment]
We have updated it in 0.9.0-beta version.
