### ISSUE TITLE
getNetworkType throwing an exception

### ISSUE THREAD

**Issue by Alex-us** [ringcentral/ringcentral-web-phone#347]
Hi there, 
If I start a new call in RC, getNetworkType  throwing an exception
![image](https://user-images.githubusercontent.com/5812272/188659793-e7e2d463-c6e9-42e2-a229-1a3e0a7395c2.png)
![image](https://user-images.githubusercontent.com/5812272/188659924-f4d09e13-3ff9-4748-8ad9-661e9063d78d.png)

Error happened because connectionType='wifi' an it cannot get networkType from undefined:
var localNetwork = connectionType.local.networkType || ['unknown'];

WebPhone.version = '0.8.11';

**Comment by Alex-us** [comment]
This is happened on new Chrome ver 105

**Comment by tylerlong** [comment]
Sorry for the late reply. We just released version 2.0. Versions before 1.x is not maintained any more.
