### ISSUE TITLE
The Number you have dialed is temporality unavailable..!

### ISSUE THREAD

**Issue by Mayank6-MG** [ringcentral/ringcentral-web-phone#368]
I'm using RingCentral Webphone. I tested it with my sandbox credentials so it is working fine means I'm able to call to a particular number ... but when I switch from sandbox to production credentials I'm getting the response where provider says that "the number you have dialed is temporarily unavailable , good bye" can you please help me out with this!

@tylerlong @creatovisguru @egreenmachine @tylerlong Thanks For your response in advanced!

**Comment by tylerlong** [comment]
Please create a ticket here https://developers.ringcentral.com/support/create-case

We won't handle it here unless we are sure it is a SDK issue. What you reported sounds more like an account issue.
Feel free to create a new ticket if you think something is wrong with the SDK.
