### ISSUE TITLE
Demo not working on Firefox 

### ISSUE THREAD

**Issue by vyshakhbabji** [ringcentral/ringcentral-web-phone#37]
Cannot run the demo on Firefox

**Comment by kirill-konshin** [comment]
List the specific issues please

**Comment by vyshakhbabji** [comment]
**While making outgoing call : **

Object { name: "INVALID_SESSION_DESCRIPTION", message: "Could not negotiate answer SDP; cause = SDP_PARSE_FAILED | SDP Parsing Error:  Warning: Transport protocol type unsupported (UDP/TLS/RTP/SAVPF). | SDP Parsing Error:  Invalid port format (19216) specified for transport protocol (Unsupported), parse failed.", __exposedProps__: Object }

This issue explains it:  
https://groups.google.com/forum/#!searchin/sip_js/Transport$20protocol$20type$20unsupported$20(UDP$2FTLS$2FRTP$2FSAVPF/sip_js/sqexozWaCL8/K5tD6Eac6jYJ

**Comment by bdeanindy** [comment]
After receiving positive Registered notification and then trying to call outbound, I'm receiving this console.log() error in Firefox v42.0:

```
WebPhone.prototype.call@http://localhost:8080/build/ringcentral-web-phone.js:398:1
startCall/<@http://localhost:8080/demo/index.js:48:17
lib$es6$promise$$internal$$tryCatch@http://localhost:8080/demo/ringcentral-bundle.js:1412:16
lib$es6$promise$$internal$$invokeCallback@http://localhost:8080/demo/ringcentral-bundle.js:1424:17
lib$es6$promise$$internal$$publish@http://localhost:8080/demo/ringcentral-bundle.js:1395:11
lib$es6$promise$asap$$flush@http://localhost:8080/demo/ringcentral-bundle.js:1206:9
```

I see the console.log above line (47) with the data which will be provided to webCall() being logged as `SIP call to 131760097331 from 16506429233`, so the numbers going in appear correct.

**Comment by bdeanindy** [comment]
I'm on Firefox version 42.0 and receiving the following warnings after granting permission to access microphone:

```
RTCIceServer.url is deprecated! Use urls instead. <unknown>
Mandatory/optional in createOffer options is deprecated! Use {} instead (note the case difference)!
```

**Comment by kirill-konshin** [comment]
See https://support.sonus.net/display/SBXDOC50/Configuring+SBC+for+WRTC section "Configuring DTLS-SRTP"

**Comment by kirill-konshin** [comment]
It is working now on Sandbox environment.
