### ISSUE TITLE
603 - Too Many Contacts

### ISSUE THREAD

**Issue by FlandersBurger** [ringcentral/ringcentral-web-phone#374]
I keep running into the below error. Is anyone else running into this? I'm not sure how to ask the right question as I don't really know the cause. Seems to happen sporadically and I have to wait a couple of minutes for it to alleviate. I assume it has to do with it establishing connections on each refresh but I don't know how to make it reuse an established connection.
Any info regarding the issue would be hugely appreciated.

"
SIP/2.0 603 Too Many Contacts
Via: SIP/2.0/WSS femcvfqh8p1f.invalid;branch=z9hG4bK6653901;received=24.108.116.162
To: sip:1##########*101@sip.devtest.ringcentral.com;tag=7BvYdcd7fcr
From: sip:1##########*101@sip.devtest.ringcentral.com;tag=vbdr8qojhl
Call-ID: 8frudde185qca0cgkkbrg1
CSeq: 3632 REGISTER
Content-Length: 0
"

**Comment by embbnux** [comment]
HI @FlandersBurger To avoid this, you need to pass a fixed instance id https://github.com/ringcentral/ringcentral-web-phone/blob/master/src/index.ts#L137
With that, when web phone reconnected, server will think it is a same connection.

**Comment by FlandersBurger** [comment]
@embbnux, Do I get this instance ID anywhere or can I just make my own?

**Comment by embbnux** [comment]
> @embbnux, Do I get this instance ID anywhere or can I just make my own?
> 
> Thanks btw, I've been stuck on this for a while and that's the first clue I've gotten online :)

Sorry for missing this. The instance ID is just a uuid. You can generate it by yourself. Instance id should be unique for different user and connection.  If you run web phone in browser with multiple tabs, it should be different at different tabs.
