### ISSUE TITLE
remove old listener when reconnect media

### ISSUE THREAD

**Issue by 563315441** [ringcentral/ringcentral-web-phone#377]
we will set a listener to trigger send reinvite and remove listener when receive a null candidate.

but for some case, such as 100% UDP lost, we can not receive the null candidate, so we will reconnect media every 5s because reinvite timeout. in this way, the listener will be set many time, once network recover, all the listener will be triggered.

we just need one listener, so we need to remove the old listener.

**Comment by tylerlong** [comment]
There is a PR to fix the issue for 0.8.x: https://github.com/ringcentral/ringcentral-web-phone/pull/376
