### ISSUE TITLE
Format Error in PUBLISH SIP

### ISSUE THREAD

**Issue by ChanJunxin** [ringcentral/ringcentral-web-phone#378]
In current version (0.8.13 & 0.9.0), if the establishment time of call is too short, WebPhone will send PUBLISH SIP with some uninitialized parameters. For example: `cpuRC=undefined;cpuOS=undefined;netType=;ram=undefined;effectiveType=4g`	
So it is necessary to initialize these parameters when before sending PUBLISH SIP

**Comment by tylerlong** [comment]
There is a PR to fix 0.8.x: https://github.com/ringcentral/ringcentral-web-phone/pull/375
