### ISSUE TITLE
Error when recording starts on outgoing calls

### ISSUE THREAD

**Issue by FlandersBurger** [ringcentral/ringcentral-web-phone#379]
I keep getting this error when I attempt to record outgoing calls. Incoming call recordings work perfectly.

The event trigger I use is 'accepted' (v 0.8.13)
`session.on('accepted', () => session.startRecord())
`

<img width="504" alt="image" src="https://user-images.githubusercontent.com/8195826/222826447-e87b240a-010c-4853-b037-2234d7c411d5.png">

**Comment by FlandersBurger** [comment]
@tylerlong , any ideas?

**Comment by FlandersBurger** [comment]
@embbnux , any ideas?

**Comment by embbnux** [comment]
Hi @FlandersBurger For some phone system, it needs to play some audio or requires user to input number before having real call connected. During that time, you can't start recording.
If you want to have call be recorded automatically, please use RingCentral's auto recording settings. https://support.ringcentral.com/mvp/admin/company-account-settings/turning-on-on-demand-automatic-call-recording.html

**Comment by FlandersBurger** [comment]
@embbnux, thanks for the reply. 
How do I test call recording if I can't record a call? (on-demand is not available in sandbox)
Can I disable the audio before the real call in sandbox?

**Comment by FlandersBurger** [comment]
Ok, so for anyone else running into this issue, it's because of the "this is a test call using a ringcentral developer account" taking 5 seconds to be announced. if you set a 5 second timeout before starting to record a call, the problem disappears and you can record calls.
