### ISSUE TITLE
unhold call queue call issue

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-web-phone#385]
1. Caller A calls a queue
2. User picks it up
3. Caller B calls a queue
4. User picks it up and Caller A is put on hold
5. User disconnects the call with Caller B
6. unhold method is called for the call with Caller A
7. unhold method resolves but the Caller A remains in  hold state

Also, we noticed that the issue occurs if Caller B is answered while there is an active call with Caller A.
If Caller A is put on hold and then Caller B is answered - there is no issue.
Also the issue occurs ONLY when answering is handled via Autoanswer.

> With 0.8.9 it does not work either. But I've made an ugly workaround:
> when I need to unhold a call I do it via rest api and it works

New update:

 - Caller A call the queue. 
- I pickup from queue via our internal backend.
- Client receives Caller's A invitation with Auto Answer header
- I accept() the session
- Caller B call the queue. 
- I pickup from queue via our internal backend.
- Client receives Caller's B invitation with Auto Answer header
- I put  Caller's A session onhold()
- I accept() Caller's B invitation
- I terminate Caller's B session
- I call RC rest api unhold ///.  ---- without that it does not unhold
- I call wephone session.unhold()
- I call session. addTrack()

**Comment by dougroutledge** [comment]
This issue isn't just related the queues, any 2nd call makes a first call on hold lose remote audio, whether it be 2 calls, or a warm transfer aborted.  The issue seems to be with the sip.js 0.20.0 but they fact any of this made it to production is scary.

**Comment by tylerlong** [comment]
Tested SDK version 2, it's not an issue any more. In version 2, each call session are isolated from each other. And they don't share `<audio/>` at all. SIP.js is not wise to not isolate call sessions.  SDK version 2 doesn't depend on SIP.js any more.
