### ISSUE TITLE
I could not send sms through ring central api. It is throw error. "errorCode" : "OAU-251",

### ISSUE THREAD

**Issue by mohammedsalmanneosme** [ringcentral/ringcentral-web-phone#386]
GuzzleHttp\Exception\ClientException: Client error: `POST https://platform.devtest.ringcentral.com/restapi/oauth/token`
resulted in a `400 Bad Request` response:
{
"error" : "unauthorized_client",
"errors" : [ {
"errorCode" : "OAU-251",
"message" : "Unauthorized for thi (truncated...)
in /var/www/html/betaapi/public_html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /var/www/html/betaapi/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(72):
GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL,
Array, NULL)
#1 /var/www/html/betaapi/public_html/vendor/guzzlehttp/promises/src/Promise.php(204):
GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/html/betaapi/public_html/vendor/guzzlehttp/promises/src/Promise.php(153):
GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /var/www/html/betaapi/public_html/vendor/guzzlehttp/promises/src/TaskQueue.php(48):
GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/html/betaapi/public_html/vendor/guzzlehttp/promises/src/Promise.php(248):
GuzzleHttp\Promise\TaskQueue->run(true)
#5 /var/www/html/betaapi/public_html/vendor/guzzlehttp/promises/src/Promise.php(224):
GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /var/www/html/betaapi/public_html/vendor/guzzlehttp/promises/src/Promise.php(269):
GuzzleHttp\Promise\Promise->waitIfPending()
#7 /var/www/html/betaapi/public_html/vendor/guzzlehttp/promises/src/Promise.php(226):
GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /var/www/html/betaapi/public_html/vendor/guzzlehttp/promises/src/Promise.php(62):
GuzzleHttp\Promise\Promise->waitIfPending()
#9 /var/www/html/betaapi/public_html/vendor/guzzlehttp/guzzle/src/Client.php(124): GuzzleHttp\Promise\Promise->wait()
#10 /var/www/html/betaapi/public_html/vendor/ringcentral/ringcentral-php/src/Http/Client.php(74):
GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array)
#11 /var/www/html/betaapi/public_html/vendor/ringcentral/ringcentral-php/src/Http/Client.php(39):
RingCentral\SDK\Http\Client->loadResponse(Object(GuzzleHttp\Psr7\Request))
#12 /var/www/html/betaapi/public_html/vendor/ringcentral/ringcentral-php/src/Platform/Platform.php(310):
RingCentral\SDK\Http\Client->send(Object(GuzzleHttp\Psr7\Request))
#13 /var/www/html/betaapi/public_html/vendor/ringcentral/ringcentral-php/src/Platform/Platform.php(434):
RingCentral\SDK\Platform\Platform->sendRequest(Object(GuzzleHttp\Psr7\Request), Array)
#14 /var/www/html/betaapi/public_html/vendor/ringcentral/ringcentral-php/src/Platform/Platform.php(212):
RingCentral\SDK\Platform\Platform->requestToken('/restapi/oauth/...', Array)
#15 /var/www/html/betaapi/public_html/sendSMS.php(38): RingCentral\SDK\Platform\Platform->login(Array)
#16 {main}

Next RingCentral\SDK\Http\ApiException: Client error: `POST
https://platform.devtest.ringcentral.com/restapi/oauth/token` resulted in a `400 Bad Request` response:
{
"error" : "unauthorized_client",
"errors" : [ {
"errorCode" : "OAU-251",
"message" : "Unauthorized for thi (truncated...)
in /var/www/html/betaapi/public_html/vendor/ringcentral/ringcentral-php/src/Http/Client.php:52
Stack trace:
#0 /var/www/html/betaapi/public_html/vendor/ringcentral/ringcentral-php/src/Platform/Platform.php(310):
RingCentral\SDK\Http\Client->send(Object(GuzzleHttp\Psr7\Request))
#1 /var/www/html/betaapi/public_html/vendor/ringcentral/ringcentral-php/src/Platform/Platform.php(434):
RingCentral\SDK\Platform\Platform->sendRequest(Object(GuzzleHttp\Psr7\Request), Array)
#2 /var/www/html/betaapi/public_html/vendor/ringcentral/ringcentral-php/src/Platform/Platform.php(212):
RingCentral\SDK\Platform\Platform->requestToken('/restapi/oauth/...', Array)
#3 /var/www/html/betaapi/public_html/sendSMS.php(38): RingCentral\SDK\Platform\Platform->login(Array)
#4 {main}Unable to authenticate to platform. Check credentials.

**Comment by tylerlong** [comment]
It seems that the issue is about the ringcentral-php SDK.

Please create a ticket here to get help: https://developers.ringcentral.com/support/create-case
