### ISSUE TITLE
ringcentral-web-phone.js file is not availabe. Where I can find this file ?

### ISSUE THREAD

**Issue by jithintom08** [ringcentral/ringcentral-web-phone#387]
Hi, 
I want to use ringcentral-web-phone in my project. as per the documentation I need to import ringcentral-web-phone.js file. But I couldn't find this file anywhere in latest code.
How can I find the file or build ? I found the file in an old commit (Dec 2018). can I use the same file ? 

Please assist me with this issue.

**Comment by tylerlong** [comment]
Nowadays it's recommended to use a bundler tool, like webpack, parcel, vite...etc.
