### ISSUE TITLE
UserMediaFailed not emitted when Request device not found error

### ISSUE THREAD

**Issue by heyflynn** [ringcentral/ringcentral-web-phone#388]
I want to catch user media errors when starting a session invite but the UserMediaFailed session event is not emitted when the device (headset) is off.

The event is only emitted when permission is denied to use the mic.

The error message when the device is off is "Requested device not found" for which I would like to prompt the user to turn on the device before making a call.

![userMediaFailed](https://github.com/ringcentral/ringcentral-web-phone/assets/553465/0f916272-1f4c-4227-9b0c-f47319002398)

**Comment by tylerlong** [comment]
Kindly try version 2.0 and re-open it if you still have this issue.

Version 2.0 doesn't catch the exception thrown by `navigator.mediaDevices.getUserMedia`. So the exception will be thrown to your app.
