### ISSUE TITLE
Does this SDK use deprecated password-based auth flow?

### ISSUE THREAD

**Issue by chhhris** [ringcentral/ringcentral-web-phone#389]
I'm looking at [the Readme](https://github.com/ringcentral/ringcentral-web-phone#:~:text=platform%0A%20%20.login(%7B%0A%20%20%20%20username%3A%20%27...%27%2C%0A%20%20%20%20password%3A%20%27...%27%2C%0A%20%20%7D)) where it appears this SDK is using the password-based API auth flow which Ringcentral [has deprecated](https://community.ringcentral.com/articles/116310/end-of-life-for-the-password-based-api-authenticat.html)?

```js
var platform = sdk.platform();

platform
  .login({
    username: '...',
    password: '...',
  })
  .then(function (loginResponse) {
  ...
 });
```

Would someone be so kind as to confirm if this is so, or if I am misunderstanding? Many thanks!

**Comment by tylerlong** [comment]
Yes, but it is only the demo code. The SDK is independent of auth flows. You may use whatever auth flow that works for you.

I have updated the readme and demo code, by the way. You can no long find password anywhere in this repo.
