### ISSUE TITLE
Party answer callback

### ISSUE THREAD

**Issue by websolutionfalcon** [ringcentral/ringcentral-web-phone#391]
Hello!
Is there any callback/event fired when the party I called via webphone is answered the call?
I want to enable some buttons on my UI (record call for example only when call is answered)

**Comment by tylerlong** [comment]
SIP server doesn't support such as event. (server side engineers said it's by design)
You will have to use subscription which is not related to this SDK.
https://developers.ringcentral.com/api-reference/Extension-Telephony-Sessions-Event

It's not the answer you expect but it's the reality.
