### ISSUE TITLE
Feature Request : Audio setup

### ISSUE THREAD

**Issue by dougroutledge** [ringcentral/ringcentral-web-phone#394]
Please add wrappers to setup the audio devices to match the RC App.
![image](https://github.com/ringcentral/ringcentral-web-phone/assets/15715959/84c2c902-40ce-4053-83b1-7920cde101a1)

**Comment by tylerlong** [comment]
In version 2.0, there is a way to change the default device for new call. There is also a way to change the device for ongoing calls.

Ref: https://github.com/ringcentral/ringcentral-web-phone?tab=readme-ov-file#audio-devices

<img width="864" alt="Screenshot 2024-11-21 at 2 31 17 PM" src="https://github.com/user-attachments/assets/b07515d7-493a-4d22-8e66-bccc3a24b1e5">

**Comment by tylerlong** [comment]
> We can already do this, but the one that is really needed is the ringing device, as many wind up setting their headset as their default audio device accidentally.

Version 2.0 doesn't play ringtone at all.  It is a by design change.
