### ISSUE TITLE
Improve error reporting when outbound calls flag is not enabled.

### ISSUE THREAD

**Issue by bdeanindy** [ringcentral/ringcentral-web-phone#41]
This is what you receive if a phone is not configured with the outbound call flags, need to add better error handling (we did this the other day, and I thought I pushed it up).

After receiving positive Registered notification and then trying to call outbound, I'm receiving this console.log() error in Firefox v42.0:

```
WebPhone.prototype.call@http://localhost:8080/build/ringcentral-web-phone.js:398:1
startCall/<@http://localhost:8080/demo/index.js:48:17
lib$es6$promise$$internal$$tryCatch@http://localhost:8080/demo/ringcentral-bundle.js:1412:16
lib$es6$promise$$internal$$invokeCallback@http://localhost:8080/demo/ringcentral-bundle.js:1424:17
lib$es6$promise$$internal$$publish@http://localhost:8080/demo/ringcentral-bundle.js:1395:11
lib$es6$promise$asap$$flush@http://localhost:8080/demo/ringcentral-bundle.js:1206:9
```

I see the console.log above line (47) with the data which will be provided to webCall() being logged as `SIP call to 131760097331 from 16506429233`, so the numbers going in appear correct.

**Comment by kirill-konshin** [comment]
Please implement this check in `invite()` method, use `clean` branch.

**Comment by bdeanindy** [comment]
I passed the beginning code changes I made for this to @vyshakhbabji and thought those were merged long ago...is that not the case?

**Comment by kirill-konshin** [comment]
This has been fixed in alpha version. Current version has different everything.

**Comment by bdeanindy** [comment]
So do we need to re-implement these changes?

**Comment by kirill-konshin** [comment]
Short answer -- yes. I hope it will be a cleaner implementation.

**Comment by bdeanindy** [comment]
Do not have time to work this issue right now, closing.
