### ISSUE TITLE
Error when country code is omitted from Auth

### ISSUE THREAD

**Issue by bdeanindy** [ringcentral/ringcentral-web-phone#42]
If you leave out the "1" and you're on an American-based number, you receive an "Invalid credentials" error from the auth request.

Need to do one or more of the following:

- Disable the `Register Sip Configurations` button in demo until all fields are correct
- Change style settings to reflect error on the fromNumber field in the UI to be in error state (use Bootstrap)
- Provide example of a 'passing' fromNumber as a placeholder
- Provide notification message above fromNumber field with details on issue

**Comment by bdeanindy** [comment]
Just tested this in Chrome, and without the country code it works alright. Might be browser-specific to Firefox.

**Comment by grokify** [comment]
One way to approach this in the UI is to allow the user to select their country and then ensure the country code is added. The RingCentral end points and Online Account Portal do this.

Once you know what country the number is associated with, you can use Google's libphonenumber library to get the E.164 formatted number.

Google: https://github.com/googlei18n/libphonenumber
Pre-built version: https://github.com/nathanhammond/libphonenumber

The CTI demo uses Nathan Hammond's pre-built version to accomplish this.

**Comment by kirill-konshin** [comment]
Fixed
