### ISSUE TITLE
Promise usage on some methods

### ISSUE THREAD

**Issue by changbenny** [ringcentral/ringcentral-web-phone#46]
```javascript
PhoneLine.prototype.cancel = function() {
    var session = this.getSession();
    return new Promise(function(resolve, reject) {
        session.terminate({statusCode: 486});
        return null;
    });
};
```
I am wondering if `resolve()` need to be called after actions finish? Such as:
```javascript
PhoneLine.prototype.cancel = function() {
    var session = this.getSession();
    return new Promise(function(resolve, reject) {
        session.terminate({statusCode: 486});
        resolve();
        return null;
    });
};
```

**Comment by kirill-konshin** [comment]
That's basically the same effect.

**Comment by changbenny** [comment]
If the promise call `resolve()`, it become thenable. Therefore, we can use the method like this:
```
phoneline.cancel().then(function() {...})
```
But currently I cannot achieve the same result, do you have some suggestions?

**Comment by kirill-konshin** [comment]
Normally Promise constructor with resolver function should always return thennable no matter `resolve` is called or plain `return`.

If you `return` a plain object synchronously it behaves the same. The difference is when you return a `thennable` -- in this case `resolve` has to be used. That's by spec. I'll look into your PR, `resolve` call is always safer.

**Comment by changbenny** [comment]
The Promise constructor without `resolve()` will be a pending promise. I think if we only want to return a plain object synchronously, there is a better way:
```
return Promise.resolve().then(function () {
    sync_action();
    return 'foo';
}).then(/* ... */);
```

**Comment by kirill-konshin** [comment]
It's better to wrap `sync_action()` in `resolve(sync_action())` assuming that sync action returns a `thennable`.
