### ISSUE TITLE
SIP.js needs to be packaged with the bundle for factory reference

### ISSUE THREAD

**Issue by bdeanindy** [ringcentral/ringcentral-web-phone#65]
Currently, looking at the demo code, the sip.js library is referenced externally from the <head> tag. This means that if you do not add this JS src in your head tag, that you will receive a SIP undefined error in JS while trying to execute demo code.

Needs to be bundled within the library itself, especially for apps which hit the 3rd conditional statement of the UMD format being used by src/ringcentral-web-phone.js (lines 9-12)

**Comment by kirill-konshin** [comment]
Take a look at backbone http://backbonejs.org/backbone.js it relies on jQuery and surely it does not bundle it.
