### ISSUE TITLE
Error in peer.createDTMFSender

### ISSUE THREAD

**Issue by mgw2007** [ringcentral/ringcentral-web-phone#77]
Hi
I try the demo and its working but when I try to send DTMF I got this error 

```
TypeError: peer.createDTMFSender is not a function
```

In [`ringcentral-web-phone.js` line 590](https://github.com/ringcentral/ringcentral-web-phone/blob/eb1eeec625e418fcebce86de02dbb48403b515e0/src/ringcentral-web-phone.js#L590)

```
var dtmfSender = peer.createDTMFSender(stream.getAudioTracks()[0]);
```

Thanks

**Comment by vyshakhbabji** [comment]
@mgw2007 it is working fine for me.   I couldn't reproduce it in the demo .. could you please turn the debug log to level 3 and send me the complete log details to devsupport@ringcentral.com ?

**Comment by mgw2007** [comment]
yes its working fine now
Thanks

**Comment by mgw2007** [comment]
Hi
I found the issue again it seems its happened on firefox and not happened on chrome
so please try it on firefox

**Comment by vyshakhbabji** [comment]
I am going to mark this as a bug.

**Comment by kirill-konshin** [comment]
Some info on this topic:
https://lists.w3.org/Archives/Public/public-webrtc/2014Nov/0069.html

After googling it seems that this is a known bug, many people face it. In order to solve it I need some more information: OS, FF version.

**Comment by mgw2007** [comment]
My OS : Ubuntu 16
Firefox  version : 48

**Comment by vyshakhbabji** [comment]
http://w3c.github.io/webrtc-pc/#peer-to-peer-dtmf 

RTCRtpDTMF sender is not implemeted in Sip. JS . 

Additoinal reference :  https://hacks.mozilla.org/2015/11/webrtc-sending-dtmf-in-firefox/  , checked the implementation but didnot work  because of above reason.

**Comment by vyshakhbabji** [comment]
We will fix this when the Firefox support becomes official

**Comment by valeriiBerezhniyCollab** [comment]
This code works for me:
`try {
              var localStream = session.connection.getLocalStreams()[0]
              if (session.connection.getSenders) {
                dtmfSender = session.connection.getSenders()[0].dtmf;
              } else {
                log(
                  "Your browser doesn't support RTCPeerConnection.getSenders(), so " +
                  "falling back to use <strong>deprecated</strong> createDTMFSender() " +
                  "instead.",
                );
                dtmfSender = session.connection.createDTMFSender(localStream.getAudioTracks()[0]);
              }
          } catch (e) {
            console.error(e.message)
          }

          session.sendDTMF = function (tone) {
            dtmfSender.insertDTMF(tone)
          }`
