### ISSUE TITLE
Calling request to.displayName its the same value of from.displayName

### ISSUE THREAD

**Issue by mgw2007** [ringcentral/ringcentral-web-phone#79]
When we make a call on the target user page this code

``` js
console.log('To', session.request.to.displayName, session.request.to.friendlyName);
console.log('From', session.request.from.displayName, session.request.from.friendlyName);
```

print the same value the name of From user

Also there is away to get the caller user extension Id ??

**Comment by vyshakhbabji** [comment]
same as issue #99 .

**Comment by vyshakhbabji** [comment]
@mgw2007  Can you please clarify this? --> "Also there is away to get the caller user extension Id ?? "

**Comment by vyshakhbabji** [comment]
No reply to the question for a long time. Closing this issue for now.
