### ISSUE TITLE
session.reject(); is not reflect on the caller side

### ISSUE THREAD

**Issue by mgw2007** [ringcentral/ringcentral-web-phone#80]
Hi
When you create a call from browser to another
when the target browser reject the call its not reflect on the other side I mean no events triggered on the caller side so the caller can not know the call is rejected

**Comment by mgw2007** [comment]
any help ?

**Comment by vyshakhbabji** [comment]
Hi , When the incoming call gets rejected ,  the call goes to voice mail. There is no event triggered to the call that routes to the voicemail as the call is still active. When the outgoing call gets rejected and the call doesn't reach the voice mail there is a event that triggers for call disconnection.

**Comment by mgw2007** [comment]
Thanks
