### ISSUE TITLE
Remove PRACK special handler

### ISSUE THREAD

**Issue by kirill-konshin** [ringcentral/ringcentral-web-phone#82]
The fix that morphs PRACK into ACK needs to be removed:

https://github.com/ringcentral/ringcentral-web-phone/blob/master/src/ringcentral-web-phone.js#L350

The options are:

1. Only remove the fix and verify that everything works OK (there might be 4xx errors in console)
2. Completely cancel the PRACK request -- this has never been tested, behavior is unpredictable

If option 1 will not produce errors, go with it, otherwise try option 2. If it will not work -- let @kirill-konshin know, so that we can find another solution.

**Comment by anilkumarbp** [comment]
Scenarion 1 produces 400 error (by the call is successful):
```
PRACK sip:xxx@xxx:5080 SIP/2.0
Route: <sip:10.29.20.4:8080;transport=ws;r2=on;lr=on;did=e11.57b>
Route: <sip:10.29.20.4:5060;r2=on;lr=on;did=e11.57b>
Via: SIP/2.0/WSS xxx.invalid;branch=xxx
Max-Forwards: 70
To: <sip:xxx@sip.devtest.ringcentral.com>;tag=xxx
From: <sip:xxx@sip.devtest.ringcentral.com>;tag=xxx
Call-ID: xxx
CSeq: 8993 PRACK
RAck: undefined 8992 INVITE
Supported: outbound
User-Agent: SIP.js/0.7.5
Content-Length: 0
```
```
SIP/2.0 400 Bad Request
Via: SIP/2.0/WSS xxx.invalid;rport=41140;received=xxx;branch=xxx
From: <sip:xxx@sip.devtest.ringcentral.com>;tag=xxx
To: <sip:18315941779@sip.devtest.ringcentral.com>;tag=xxx
Call-ID: xxx
CSeq: 8993 PRACK
Error-Info: <sip:xxx@xxx>;cause="[line 009] SIP syntax error"
Content-Length: 0
```

Scenarion 2 produces 401 Unauthorized and 407 Proxy Authentication Required ( but no PRACK Error )

HTTP 401Unauthorized
```
SIP/2.0 401 Unauthorized
Via: SIP/2.0/WSS xxx.invalid;rport=48477;received=xxx;branch=xxx
From: <sip:xxx@sip.devtest.ringcentral.com>;tag=xxx
To: <sip:xxx@sip.devtest.ringcentral.com>;tag=xxx
Call-ID: xxx
CSeq: 82 REGISTER
WWW-Authenticate: Digest realm="sip.devtest.ringcentral.com",nonce="V+mg+1fpn88wNjV0YFOR9J5tMcnRz1p0"
Content-Length: 0
```

HTTP 407 Proxy Authentication Required
```
SIP/2.0 407 Proxy Authentication Required
Via: SIP/2.0/WSS xxx.invalid;rport=48477;received=xxx;branch=xxx
From: <sip:xxx@sip.devtest.ringcentral.com>;tag=xxx
To: <sip:xxx@sip.devtest.ringcentral.com>;tag=xxx
Call-ID: xxx
CSeq: 8508 INVITE
Proxy-Authenticate: Digest realm="sip.devtest.ringcentral.com",nonce="V+mhD1fpn+MwogkIOhnlPqm935vk+yhM"
Content-Length: 0
```

**Comment by kirill-konshin** [comment]
Library used to have PRACK treatment back in the days: https://github.com/ringcentral/ringcentral-web-phone/blob/d6c3b031e2eac55cffd5519e5dac5516efa31cdd/src/web-phone.js#L646
