### ISSUE TITLE
Remove custom handling of JSON

### ISSUE THREAD

**Issue by kirill-konshin** [ringcentral/ringcentral-web-phone#90]
Remove custom handling of JSON, replace with mediaHandler patches.
## sendReceive

https://github.com/ringcentral/ringcentral-web-phone/blob/master/src/ringcentral-web-phone.js#L288

This function is used for recording, flip & park.

We need an ability to receive JSON body with the same CSEQ and get it as promise. This function works in conjunction with the following `receiveRequest`: it uses `RC_SIP_INFO` event and JSON handling.
## blindTransfer

https://github.com/ringcentral/ringcentral-web-phone/blob/master/src/ringcentral-web-phone.js#L590

I strongly suspect that blind transfer could be replaced with something native in SIP.JS. This function also works in conjunction with the following `receiveRequest`, it uses `RC_SIP_NOTIFY` event.
## receiveRequest

https://github.com/ringcentral/ringcentral-web-phone/blob/master/src/ringcentral-web-phone.js#L458
This function is used to emit `RC_SIP_INFO` event which is captured in `sendReceive` and `RC_SIP_NOTIFY` which is used in `blindTransfer`.

Also it has some custom handling for re-INVITES: refresh invite should not be rejected with 488.

**Comment by vyshakhbabji** [comment]
Implemented with sipjs0.10.0 bilndtransfer function
