### ISSUE TITLE
Cannot read property 'UA' of undefined error at new WebPhone in register method

### ISSUE THREAD

**Issue by srigottipati** [ringcentral/ringcentral-web-phone#96]
Hi,

I am getting "Cannot read property 'UA' of undefined" error at new WebPhone in register method.

following is my code:

try{
    sipInfo = data.sipInfo[0] || data.sipInfo;
    }catch(e){}
    webPhone = new RingCentral.WebPhone(data,{
        appKey: rc_platform._appKey,
        audioHelper: {
                            enabled: true
            
        },
        logLevel: 3
    });

Thanks in advance.

Sri

**Comment by kirill-konshin** [comment]
Have you added SIP.JS library to your page? Please copy-paste exact error message with line number.

**Comment by srigottipati** [comment]
I have included sip-0.7.5.min.js file.

Getting error at  
this.userAgent = new SIP.UA(configuration).register({
            extraHeaders: [
                this.endpointHeader,
                this.userAgentHeader,
                this.clientIdHeader
            ]
        });
 in ring central-web-phone.js.

error message: "Cannot read property 'UA' of undefined"
stack: typeError: Cannot read property 'UA' of undefined↵    at new WebPhone (http://localhost:8888/flatfull/lib/ringcentral/ringcentral-web-phone.js:169:33)

Thanks in advance

**Comment by kirill-konshin** [comment]
What version of WebPhone are you using?

**Comment by srigottipati** [comment]
yup...got it...thanks @kirill-konshin
